# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.53
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/23722608885
# Commit: https://github.com/zenopie/erth-network-app/commit/76e3b97851c33cde4acae9ae9e11ae8e5cb856c6
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:95092072510e9292bc45f558cd065c1b9236bf5282d91e99c42b5a39df871198
    ports:
      - '80'
