# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.58
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/24098091423
# Commit: https://github.com/zenopie/erth-network-app/commit/8cd12dd820d4603b76f6ae9472dcd2bb9aac541e
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:a213f0dbf24b813448dab15d02c3fc9a99508718f0aa7139c98bab4d206026f5
    ports:
      - '80'
