# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.50
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/23492765134
# Commit: https://github.com/zenopie/erth-network-app/commit/eea179d1ca68e22542584db29b754dbb591eb05c
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:878f462e6440e053b88f089d89a028290caa62a1315b419a8c1a20734d2e5369
    ports:
      - '80'
