// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: earth/allocation/v1/allocation.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "earth.allocation.v1";

/**
 * StreamId selects which emission stream a message or piece of state belongs to.
 *
 * The two streams run the same engine over separate state; they differ only in
 * where a voter's weight comes from and who is allowed to vote at all.
 */
export enum StreamId {
  /** STREAM_ID_UNSPECIFIED - STREAM_ID_UNSPECIFIED is an invalid default; every message must name a stream. */
  STREAM_ID_UNSPECIFIED = 0,
  /**
   * STREAM_ID_CARETAKER - STREAM_ID_CARETAKER is the Caretaker Fund: one human, one vote. Weight
   * comes from a live proof-of-personhood registration and is the same for
   * every human.
   *
   * Numbered 1 as it always was. The name changed, the wire did not — enums
   * travel as numbers, so existing state and any in-flight message decode
   * unchanged. What does change is the JSON the LCD emits and accepts, since
   * grpc-gateway spells enums by name.
   */
  STREAM_ID_CARETAKER = 1,
  /**
   * STREAM_ID_GROUNDWORKS - STREAM_ID_GROUNDWORKS is the Groundworks Fund: stake-weighted. Weight is
   * the voter's bonded stake, normalized by the stake compounding index.
   */
  STREAM_ID_GROUNDWORKS = 2,
  UNRECOGNIZED = -1,
}

export function streamIdFromJSON(object: any): StreamId {
  switch (object) {
    case 0:
    case "STREAM_ID_UNSPECIFIED":
      return StreamId.STREAM_ID_UNSPECIFIED;
    case 1:
    case "STREAM_ID_CARETAKER":
      return StreamId.STREAM_ID_CARETAKER;
    case 2:
    case "STREAM_ID_GROUNDWORKS":
      return StreamId.STREAM_ID_GROUNDWORKS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return StreamId.UNRECOGNIZED;
  }
}

export function streamIdToJSON(object: StreamId): string {
  switch (object) {
    case StreamId.STREAM_ID_UNSPECIFIED:
      return "STREAM_ID_UNSPECIFIED";
    case StreamId.STREAM_ID_CARETAKER:
      return "STREAM_ID_CARETAKER";
    case StreamId.STREAM_ID_GROUNDWORKS:
      return "STREAM_ID_GROUNDWORKS";
    case StreamId.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** AllocationKind identifies how an allocation option delivers its accrued ERTH. */
export enum AllocationKind {
  /** ALLOCATION_KIND_UNSPECIFIED - ALLOCATION_KIND_UNSPECIFIED is an invalid default. */
  ALLOCATION_KIND_UNSPECIFIED = 0,
  /**
   * ALLOCATION_KIND_INTEGRATED - ALLOCATION_KIND_INTEGRATED resolves automatically every block via a protocol
   * handler selected by `handler` (e.g. "lp_rewards"). Governance-permissioned to add.
   */
  ALLOCATION_KIND_INTEGRATED = 1,
  /**
   * ALLOCATION_KIND_ADDRESS - ALLOCATION_KIND_ADDRESS accrues ERTH claimable by a fixed recipient address.
   * Permissionless to add (guarded by an address-option fee).
   */
  ALLOCATION_KIND_ADDRESS = 2,
  UNRECOGNIZED = -1,
}

export function allocationKindFromJSON(object: any): AllocationKind {
  switch (object) {
    case 0:
    case "ALLOCATION_KIND_UNSPECIFIED":
      return AllocationKind.ALLOCATION_KIND_UNSPECIFIED;
    case 1:
    case "ALLOCATION_KIND_INTEGRATED":
      return AllocationKind.ALLOCATION_KIND_INTEGRATED;
    case 2:
    case "ALLOCATION_KIND_ADDRESS":
      return AllocationKind.ALLOCATION_KIND_ADDRESS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AllocationKind.UNRECOGNIZED;
  }
}

export function allocationKindToJSON(object: AllocationKind): string {
  switch (object) {
    case AllocationKind.ALLOCATION_KIND_UNSPECIFIED:
      return "ALLOCATION_KIND_UNSPECIFIED";
    case AllocationKind.ALLOCATION_KIND_INTEGRATED:
      return "ALLOCATION_KIND_INTEGRATED";
    case AllocationKind.ALLOCATION_KIND_ADDRESS:
      return "ALLOCATION_KIND_ADDRESS";
    case AllocationKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * AllocationOption is a destination voters can direct an emission stream to.
 * Ids are per stream: option #1 of the human stream and option #1 of the capital
 * stream are different options.
 */
export interface AllocationOption {
  id: number;
  /** stream is the emission stream this option draws from. */
  stream: StreamId;
  description: string;
  kind: AllocationKind;
  /** recipient is the payout address for ADDRESS options (unused for INTEGRATED). */
  recipient: string;
  /**
   * handler selects the per-block behaviour for INTEGRATED options (e.g.
   * "lp_rewards"); empty for ADDRESS options.
   */
  handler: string;
  /**
   * claimer optionally restricts who may trigger a claim on an ADDRESS option.
   * Empty (the default) means anyone may trigger it. Either way the payout goes
   * to `recipient` — a claimer only spends the gas.
   */
  claimer: string;
  /** amount_allocated is the total voting weight currently directed at this option. */
  amountAllocated: string;
  /** last_reward_index is the stream's reward index at this option's last settlement. */
  lastRewardIndex: string;
  /** accumulated is ERTH (uerth) owed to this option, awaiting distribution/claim. */
  accumulated: string;
}

/** AllocationWeight is one entry of a voter's split. */
export interface AllocationWeight {
  optionId: number;
  /** percent is 0-100; a voter's weights must sum to 100. */
  percent: number;
}

/**
 * Voter records one address's split within one stream, and the weight it was
 * applied with. The human stream applies the same fixed weight to everyone; the
 * capital stream applies the voter's normalized bonded stake, kept in sync by
 * the staking hooks.
 */
export interface Voter {
  percentages: AllocationWeight[];
  weight: string;
  /**
   * epoch is the stream's allocation epoch this split was cast in. A governance
   * reset bumps that epoch and zeroes the aggregates in one cheap operation
   * rather than rewriting every voter row; a record from an older epoch is
   * treated as having no live contribution, so re-voting starts from zero
   * instead of subtracting weight that has already been cleared. Epochs are per
   * stream: resetting one stream leaves the other untouched.
   */
  epoch: number;
}

function createBaseAllocationOption(): AllocationOption {
  return {
    id: 0,
    stream: 0,
    description: "",
    kind: 0,
    recipient: "",
    handler: "",
    claimer: "",
    amountAllocated: "",
    lastRewardIndex: "",
    accumulated: "",
  };
}

export const AllocationOption: MessageFns<AllocationOption> = {
  encode(message: AllocationOption, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.stream !== 0) {
      writer.uint32(80).int32(message.stream);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.kind !== 0) {
      writer.uint32(24).int32(message.kind);
    }
    if (message.recipient !== "") {
      writer.uint32(34).string(message.recipient);
    }
    if (message.handler !== "") {
      writer.uint32(66).string(message.handler);
    }
    if (message.claimer !== "") {
      writer.uint32(74).string(message.claimer);
    }
    if (message.amountAllocated !== "") {
      writer.uint32(42).string(message.amountAllocated);
    }
    if (message.lastRewardIndex !== "") {
      writer.uint32(50).string(message.lastRewardIndex);
    }
    if (message.accumulated !== "") {
      writer.uint32(58).string(message.accumulated);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AllocationOption {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseAllocationOption();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.id = longToNumber(reader.uint64());
            continue;
          }
          case 10: {
            if (tag !== 80) {
              break;
            }

            message.stream = reader.int32() as any;
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.description = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.kind = reader.int32() as any;
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.recipient = reader.string();
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.handler = reader.string();
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.claimer = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.amountAllocated = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.lastRewardIndex = reader.string();
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.accumulated = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): AllocationOption {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      stream: isSet(object.stream) ? streamIdFromJSON(object.stream) : 0,
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      kind: isSet(object.kind) ? allocationKindFromJSON(object.kind) : 0,
      recipient: isSet(object.recipient) ? globalThis.String(object.recipient) : "",
      handler: isSet(object.handler) ? globalThis.String(object.handler) : "",
      claimer: isSet(object.claimer) ? globalThis.String(object.claimer) : "",
      amountAllocated: isSet(object.amountAllocated)
        ? globalThis.String(object.amountAllocated)
        : isSet(object.amount_allocated)
        ? globalThis.String(object.amount_allocated)
        : "",
      lastRewardIndex: isSet(object.lastRewardIndex)
        ? globalThis.String(object.lastRewardIndex)
        : isSet(object.last_reward_index)
        ? globalThis.String(object.last_reward_index)
        : "",
      accumulated: isSet(object.accumulated) ? globalThis.String(object.accumulated) : "",
    };
  },

  toJSON(message: AllocationOption): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.stream !== 0) {
      obj.stream = streamIdToJSON(message.stream);
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.kind !== 0) {
      obj.kind = allocationKindToJSON(message.kind);
    }
    if (message.recipient !== "") {
      obj.recipient = message.recipient;
    }
    if (message.handler !== "") {
      obj.handler = message.handler;
    }
    if (message.claimer !== "") {
      obj.claimer = message.claimer;
    }
    if (message.amountAllocated !== "") {
      obj.amountAllocated = message.amountAllocated;
    }
    if (message.lastRewardIndex !== "") {
      obj.lastRewardIndex = message.lastRewardIndex;
    }
    if (message.accumulated !== "") {
      obj.accumulated = message.accumulated;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AllocationOption>, I>>(base?: I): AllocationOption {
    return AllocationOption.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AllocationOption>, I>>(object: I): AllocationOption {
    const message = createBaseAllocationOption();
    message.id = object.id ?? 0;
    message.stream = object.stream ?? 0;
    message.description = object.description ?? "";
    message.kind = object.kind ?? 0;
    message.recipient = object.recipient ?? "";
    message.handler = object.handler ?? "";
    message.claimer = object.claimer ?? "";
    message.amountAllocated = object.amountAllocated ?? "";
    message.lastRewardIndex = object.lastRewardIndex ?? "";
    message.accumulated = object.accumulated ?? "";
    return message;
  },
};

function createBaseAllocationWeight(): AllocationWeight {
  return { optionId: 0, percent: 0 };
}

export const AllocationWeight: MessageFns<AllocationWeight> = {
  encode(message: AllocationWeight, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.optionId !== 0) {
      writer.uint32(8).uint64(message.optionId);
    }
    if (message.percent !== 0) {
      writer.uint32(16).uint64(message.percent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AllocationWeight {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseAllocationWeight();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.optionId = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.percent = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): AllocationWeight {
    return {
      optionId: isSet(object.optionId)
        ? globalThis.Number(object.optionId)
        : isSet(object.option_id)
        ? globalThis.Number(object.option_id)
        : 0,
      percent: isSet(object.percent) ? globalThis.Number(object.percent) : 0,
    };
  },

  toJSON(message: AllocationWeight): unknown {
    const obj: any = {};
    if (message.optionId !== 0) {
      obj.optionId = Math.round(message.optionId);
    }
    if (message.percent !== 0) {
      obj.percent = Math.round(message.percent);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AllocationWeight>, I>>(base?: I): AllocationWeight {
    return AllocationWeight.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AllocationWeight>, I>>(object: I): AllocationWeight {
    const message = createBaseAllocationWeight();
    message.optionId = object.optionId ?? 0;
    message.percent = object.percent ?? 0;
    return message;
  },
};

function createBaseVoter(): Voter {
  return { percentages: [], weight: "", epoch: 0 };
}

export const Voter: MessageFns<Voter> = {
  encode(message: Voter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.percentages) {
      AllocationWeight.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.weight !== "") {
      writer.uint32(18).string(message.weight);
    }
    if (message.epoch !== 0) {
      writer.uint32(24).uint64(message.epoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Voter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseVoter();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.percentages.push(AllocationWeight.decode(reader, reader.uint32()));
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.weight = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.epoch = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Voter {
    return {
      percentages: globalThis.Array.isArray(object?.percentages)
        ? object.percentages.map((e: any) => AllocationWeight.fromJSON(e))
        : [],
      weight: isSet(object.weight) ? globalThis.String(object.weight) : "",
      epoch: isSet(object.epoch) ? globalThis.Number(object.epoch) : 0,
    };
  },

  toJSON(message: Voter): unknown {
    const obj: any = {};
    if (message.percentages?.length) {
      obj.percentages = message.percentages.map((e) => AllocationWeight.toJSON(e));
    }
    if (message.weight !== "") {
      obj.weight = message.weight;
    }
    if (message.epoch !== 0) {
      obj.epoch = Math.round(message.epoch);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Voter>, I>>(base?: I): Voter {
    return Voter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Voter>, I>>(object: I): Voter {
    const message = createBaseVoter();
    message.percentages = object.percentages?.map((e) => AllocationWeight.fromPartial(e)) || [];
    message.weight = object.weight ?? "";
    message.epoch = object.epoch ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
