// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: earth/dex/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "earth.dex.v1";

/** Params defines the parameters for the module. */
export interface Params {
  /**
   * swap_fee is the swap fee as a percentage (points of percent): "0.3" means a
   * 0.3% fee. It is charged in ERTH on every hop; half stays in the pool for the
   * liquidity providers and half is burned.
   */
  swapFee: string;
  /**
   * lp_unbonding_seconds is how long a liquidity withdrawal waits before it is
   * swept to the provider's wallet. Liquidity keeps working for the pool for the
   * whole period, so this is what makes depth sticky rather than flight-prone.
   */
  lpUnbondingSeconds: number;
}

function createBaseParams(): Params {
  return { swapFee: "", lpUnbondingSeconds: 0 };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.swapFee !== "") {
      writer.uint32(10).string(message.swapFee);
    }
    if (message.lpUnbondingSeconds !== 0) {
      writer.uint32(16).uint64(message.lpUnbondingSeconds);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.swapFee = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.lpUnbondingSeconds = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      swapFee: isSet(object.swapFee)
        ? globalThis.String(object.swapFee)
        : isSet(object.swap_fee)
        ? globalThis.String(object.swap_fee)
        : "",
      lpUnbondingSeconds: isSet(object.lpUnbondingSeconds)
        ? globalThis.Number(object.lpUnbondingSeconds)
        : isSet(object.lp_unbonding_seconds)
        ? globalThis.Number(object.lp_unbonding_seconds)
        : 0,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.swapFee !== "") {
      obj.swapFee = message.swapFee;
    }
    if (message.lpUnbondingSeconds !== 0) {
      obj.lpUnbondingSeconds = Math.round(message.lpUnbondingSeconds);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.swapFee = object.swapFee ?? "";
    message.lpUnbondingSeconds = object.lpUnbondingSeconds ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
