// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: earth/dex/v1/pool.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Coin } from "../../../cosmos/base/v1beta1/coin";

export const protobufPackage = "earth.dex.v1";

/**
 * Pool defines a spoke-and-wheel liquidity pool that always pairs the hub asset
 * (the staking coin, ERTH) with a single spoke token.
 */
export interface Pool {
  poolId: number;
  /** reserve_erth is the hub-side reserve, denominated in the staking coin. */
  reserveErth:
    | Coin
    | undefined;
  /** reserve_token is the spoke-side reserve. */
  reserveToken:
    | Coin
    | undefined;
  /**
   * volume_weight is this pool's share of the LP reward denominator. It is NOT
   * ERTH and it is NOT decayed: it is swap volume multiplied by the chain-wide
   * VolumeIndex at the moment it was recorded, so a trade today is worth 14/13
   * of one yesterday without anything having to go back and reduce the old
   * figure. See x/dex/keeper/lp_rewards.go.
   *
   * The scale cancels in `volume_weight / LpTotalVolume`, which is the only
   * thing the chain does with it, but it grows without bound in absolute terms
   * — so it is meaningless on its own and never leaves the module. Queries
   * return PoolView.volume_erth, which is this figure de-scaled back into real
   * uerth.
   */
  volumeWeight: string;
  /**
   * last_traded_day is the day index (block time / 86400) at which
   * volume_weight was last written.
   *
   * A write stamp, not a decay marker: nothing is aged from it, and a client
   * that treats it as "volume was last decayed here" will compute a decay the
   * chain does not perform. It exists so the staleness sweep knows when a pool
   * last traded.
   */
  lastTradedDay: number;
}

/**
 * PolBurn is the schedule that retires the protocol's own liquidity in a pool.
 *
 * Protocol-owned liquidity is the LP shares held by the dex module account,
 * which has no key and so can never send a MsgRemoveLiquidity. Those positions
 * are not permanent after all: this schedule burns them down to nothing on a
 * straight line, so the protocol bootstraps a market and then hands it over.
 * Providing liquidity is active management whose incentives do not line up with
 * ERTH staking, and the protocol is the worst possible manager of it; retiring
 * its own position is what leaves room for LPs who will actually run the book.
 *
 * Retiring a slice of the position withdraws that slice's share of the reserves
 * and burns it, so the pool thins without its price moving.
 */
export interface PolBurn {
  poolId: number;
  /**
   * total_shares is the size of the position when the schedule started. It is
   * the base of the straight line and never changes, so the amount retired is
   * total_shares * elapsed / duration_seconds -- a target computed from the
   * clock rather than accumulated per block. Chain halts and variable block
   * times therefore cannot make the schedule drift off its ten-year end date.
   */
  totalShares: string;
  /**
   * shares_remaining is how much of the position is left. The schedule is
   * finished, and the entry deleted, when it reaches zero.
   */
  sharesRemaining: string;
  /**
   * start_time is when the line begins, in unix seconds. Zero means "the first
   * block that sees this entry", which is how the genesis pool's schedule is
   * written: the genesis file cannot know the chain's first block time.
   */
  startTime: number;
  /** duration_seconds is how long the position takes to retire completely. */
  durationSeconds: number;
  /**
   * burn_token says whether the spoke side of each retired slice is burned too.
   *
   * True for the genesis ANML/ERTH pool: both assets are the chain's own, so
   * both are destroyed and the pool unwinds evenly to nothing.
   *
   * False for the auction pool, whose spoke side is a bridged asset the chain
   * cannot recreate. Its ERTH is burned and the spoke asset is left in the
   * reserve, which walks the pool's price up and invites arbitrageurs to sell
   * ERTH in and take the spoke asset out. The effect is that the auction's
   * proceeds are spent buying ERTH off the market, and the ERTH they buy is
   * burned by the tranches that follow. The protocol never gets a treasury it
   * could spend, because a protocol swap against its own pool cannot move the
   * spoke asset out -- only an outside buyer can.
   */
  burnToken: boolean;
}

function createBasePool(): Pool {
  return { poolId: 0, reserveErth: undefined, reserveToken: undefined, volumeWeight: "", lastTradedDay: 0 };
}

export const Pool: MessageFns<Pool> = {
  encode(message: Pool, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.poolId !== 0) {
      writer.uint32(8).uint64(message.poolId);
    }
    if (message.reserveErth !== undefined) {
      Coin.encode(message.reserveErth, writer.uint32(18).fork()).join();
    }
    if (message.reserveToken !== undefined) {
      Coin.encode(message.reserveToken, writer.uint32(26).fork()).join();
    }
    if (message.volumeWeight !== "") {
      writer.uint32(34).string(message.volumeWeight);
    }
    if (message.lastTradedDay !== 0) {
      writer.uint32(40).uint64(message.lastTradedDay);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Pool {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePool();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.poolId = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.reserveErth = Coin.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.reserveToken = Coin.decode(reader, reader.uint32());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.volumeWeight = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.lastTradedDay = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Pool {
    return {
      poolId: isSet(object.poolId)
        ? globalThis.Number(object.poolId)
        : isSet(object.pool_id)
        ? globalThis.Number(object.pool_id)
        : 0,
      reserveErth: isSet(object.reserveErth)
        ? Coin.fromJSON(object.reserveErth)
        : isSet(object.reserve_erth)
        ? Coin.fromJSON(object.reserve_erth)
        : undefined,
      reserveToken: isSet(object.reserveToken)
        ? Coin.fromJSON(object.reserveToken)
        : isSet(object.reserve_token)
        ? Coin.fromJSON(object.reserve_token)
        : undefined,
      volumeWeight: isSet(object.volumeWeight)
        ? globalThis.String(object.volumeWeight)
        : isSet(object.volume_weight)
        ? globalThis.String(object.volume_weight)
        : "",
      lastTradedDay: isSet(object.lastTradedDay)
        ? globalThis.Number(object.lastTradedDay)
        : isSet(object.last_traded_day)
        ? globalThis.Number(object.last_traded_day)
        : 0,
    };
  },

  toJSON(message: Pool): unknown {
    const obj: any = {};
    if (message.poolId !== 0) {
      obj.poolId = Math.round(message.poolId);
    }
    if (message.reserveErth !== undefined) {
      obj.reserveErth = Coin.toJSON(message.reserveErth);
    }
    if (message.reserveToken !== undefined) {
      obj.reserveToken = Coin.toJSON(message.reserveToken);
    }
    if (message.volumeWeight !== "") {
      obj.volumeWeight = message.volumeWeight;
    }
    if (message.lastTradedDay !== 0) {
      obj.lastTradedDay = Math.round(message.lastTradedDay);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Pool>, I>>(base?: I): Pool {
    return Pool.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Pool>, I>>(object: I): Pool {
    const message = createBasePool();
    message.poolId = object.poolId ?? 0;
    message.reserveErth = (object.reserveErth !== undefined && object.reserveErth !== null)
      ? Coin.fromPartial(object.reserveErth)
      : undefined;
    message.reserveToken = (object.reserveToken !== undefined && object.reserveToken !== null)
      ? Coin.fromPartial(object.reserveToken)
      : undefined;
    message.volumeWeight = object.volumeWeight ?? "";
    message.lastTradedDay = object.lastTradedDay ?? 0;
    return message;
  },
};

function createBasePolBurn(): PolBurn {
  return { poolId: 0, totalShares: "", sharesRemaining: "", startTime: 0, durationSeconds: 0, burnToken: false };
}

export const PolBurn: MessageFns<PolBurn> = {
  encode(message: PolBurn, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.poolId !== 0) {
      writer.uint32(8).uint64(message.poolId);
    }
    if (message.totalShares !== "") {
      writer.uint32(18).string(message.totalShares);
    }
    if (message.sharesRemaining !== "") {
      writer.uint32(26).string(message.sharesRemaining);
    }
    if (message.startTime !== 0) {
      writer.uint32(32).int64(message.startTime);
    }
    if (message.durationSeconds !== 0) {
      writer.uint32(40).int64(message.durationSeconds);
    }
    if (message.burnToken !== false) {
      writer.uint32(48).bool(message.burnToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PolBurn {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePolBurn();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.poolId = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.totalShares = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.sharesRemaining = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.startTime = longToNumber(reader.int64());
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.durationSeconds = longToNumber(reader.int64());
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.burnToken = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): PolBurn {
    return {
      poolId: isSet(object.poolId)
        ? globalThis.Number(object.poolId)
        : isSet(object.pool_id)
        ? globalThis.Number(object.pool_id)
        : 0,
      totalShares: isSet(object.totalShares)
        ? globalThis.String(object.totalShares)
        : isSet(object.total_shares)
        ? globalThis.String(object.total_shares)
        : "",
      sharesRemaining: isSet(object.sharesRemaining)
        ? globalThis.String(object.sharesRemaining)
        : isSet(object.shares_remaining)
        ? globalThis.String(object.shares_remaining)
        : "",
      startTime: isSet(object.startTime)
        ? globalThis.Number(object.startTime)
        : isSet(object.start_time)
        ? globalThis.Number(object.start_time)
        : 0,
      durationSeconds: isSet(object.durationSeconds)
        ? globalThis.Number(object.durationSeconds)
        : isSet(object.duration_seconds)
        ? globalThis.Number(object.duration_seconds)
        : 0,
      burnToken: isSet(object.burnToken)
        ? globalThis.Boolean(object.burnToken)
        : isSet(object.burn_token)
        ? globalThis.Boolean(object.burn_token)
        : false,
    };
  },

  toJSON(message: PolBurn): unknown {
    const obj: any = {};
    if (message.poolId !== 0) {
      obj.poolId = Math.round(message.poolId);
    }
    if (message.totalShares !== "") {
      obj.totalShares = message.totalShares;
    }
    if (message.sharesRemaining !== "") {
      obj.sharesRemaining = message.sharesRemaining;
    }
    if (message.startTime !== 0) {
      obj.startTime = Math.round(message.startTime);
    }
    if (message.durationSeconds !== 0) {
      obj.durationSeconds = Math.round(message.durationSeconds);
    }
    if (message.burnToken !== false) {
      obj.burnToken = message.burnToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PolBurn>, I>>(base?: I): PolBurn {
    return PolBurn.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PolBurn>, I>>(object: I): PolBurn {
    const message = createBasePolBurn();
    message.poolId = object.poolId ?? 0;
    message.totalShares = object.totalShares ?? "";
    message.sharesRemaining = object.sharesRemaining ?? "";
    message.startTime = object.startTime ?? 0;
    message.durationSeconds = object.durationSeconds ?? 0;
    message.burnToken = object.burnToken ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
