// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: earth/dex/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Coin } from "../../../cosmos/base/v1beta1/coin";
import { Params } from "./params";

export const protobufPackage = "earth.dex.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /** NOTE: All parameters must be supplied. */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgCreatePool defines the MsgCreatePool message. */
export interface MsgCreatePool {
  creator: string;
  amountA: Coin | undefined;
  amountB: Coin | undefined;
}

/** MsgCreatePoolResponse defines the MsgCreatePoolResponse message. */
export interface MsgCreatePoolResponse {
  poolId: number;
}

/** MsgAddLiquidity defines the MsgAddLiquidity message. */
export interface MsgAddLiquidity {
  creator: string;
  poolId: number;
  amountA: Coin | undefined;
  amountB: Coin | undefined;
}

/** MsgAddLiquidityResponse defines the MsgAddLiquidityResponse message. */
export interface MsgAddLiquidityResponse {
  shares: Coin | undefined;
}

/** MsgRemoveLiquidity defines the MsgRemoveLiquidity message. */
export interface MsgRemoveLiquidity {
  creator: string;
  poolId: number;
  /** shares is the amount of LP shares to burn. */
  shares: Coin | undefined;
}

/**
 * MsgRemoveLiquidityResponse defines the MsgRemoveLiquidityResponse message.
 *
 * No amounts are returned: the payout is priced when the unbonding matures, not
 * when it starts, because the shares keep earning and stay exposed to the pool
 * in the meantime.
 */
export interface MsgRemoveLiquidityResponse {
  /**
   * completion_time is the unix timestamp (seconds) at which the liquidity is
   * swept to the provider's wallet.
   */
  completionTime: number;
}

/**
 * MsgSwap swaps token_in for denom_out. The dex routes through the ERTH hub, so
 * a token->token swap is executed as two hops (token_in->ERTH->denom_out).
 */
export interface MsgSwap {
  creator: string;
  tokenIn: Coin | undefined;
  denomOut: string;
  minAmountOut: string;
}

/** MsgSwapResponse defines the MsgSwapResponse message. */
export interface MsgSwapResponse {
  tokenOut: Coin | undefined;
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgCreatePool(): MsgCreatePool {
  return { creator: "", amountA: undefined, amountB: undefined };
}

export const MsgCreatePool: MessageFns<MsgCreatePool> = {
  encode(message: MsgCreatePool, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.amountA !== undefined) {
      Coin.encode(message.amountA, writer.uint32(18).fork()).join();
    }
    if (message.amountB !== undefined) {
      Coin.encode(message.amountB, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreatePool {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreatePool();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.amountA = Coin.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.amountB = Coin.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreatePool {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      amountA: isSet(object.amountA)
        ? Coin.fromJSON(object.amountA)
        : isSet(object.amount_a)
        ? Coin.fromJSON(object.amount_a)
        : undefined,
      amountB: isSet(object.amountB)
        ? Coin.fromJSON(object.amountB)
        : isSet(object.amount_b)
        ? Coin.fromJSON(object.amount_b)
        : undefined,
    };
  },

  toJSON(message: MsgCreatePool): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.amountA !== undefined) {
      obj.amountA = Coin.toJSON(message.amountA);
    }
    if (message.amountB !== undefined) {
      obj.amountB = Coin.toJSON(message.amountB);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreatePool>, I>>(base?: I): MsgCreatePool {
    return MsgCreatePool.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreatePool>, I>>(object: I): MsgCreatePool {
    const message = createBaseMsgCreatePool();
    message.creator = object.creator ?? "";
    message.amountA = (object.amountA !== undefined && object.amountA !== null)
      ? Coin.fromPartial(object.amountA)
      : undefined;
    message.amountB = (object.amountB !== undefined && object.amountB !== null)
      ? Coin.fromPartial(object.amountB)
      : undefined;
    return message;
  },
};

function createBaseMsgCreatePoolResponse(): MsgCreatePoolResponse {
  return { poolId: 0 };
}

export const MsgCreatePoolResponse: MessageFns<MsgCreatePoolResponse> = {
  encode(message: MsgCreatePoolResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.poolId !== 0) {
      writer.uint32(8).uint64(message.poolId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreatePoolResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreatePoolResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.poolId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreatePoolResponse {
    return {
      poolId: isSet(object.poolId)
        ? globalThis.Number(object.poolId)
        : isSet(object.pool_id)
        ? globalThis.Number(object.pool_id)
        : 0,
    };
  },

  toJSON(message: MsgCreatePoolResponse): unknown {
    const obj: any = {};
    if (message.poolId !== 0) {
      obj.poolId = Math.round(message.poolId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreatePoolResponse>, I>>(base?: I): MsgCreatePoolResponse {
    return MsgCreatePoolResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreatePoolResponse>, I>>(object: I): MsgCreatePoolResponse {
    const message = createBaseMsgCreatePoolResponse();
    message.poolId = object.poolId ?? 0;
    return message;
  },
};

function createBaseMsgAddLiquidity(): MsgAddLiquidity {
  return { creator: "", poolId: 0, amountA: undefined, amountB: undefined };
}

export const MsgAddLiquidity: MessageFns<MsgAddLiquidity> = {
  encode(message: MsgAddLiquidity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.poolId !== 0) {
      writer.uint32(16).uint64(message.poolId);
    }
    if (message.amountA !== undefined) {
      Coin.encode(message.amountA, writer.uint32(26).fork()).join();
    }
    if (message.amountB !== undefined) {
      Coin.encode(message.amountB, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAddLiquidity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAddLiquidity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.poolId = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.amountA = Coin.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amountB = Coin.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgAddLiquidity {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      poolId: isSet(object.poolId)
        ? globalThis.Number(object.poolId)
        : isSet(object.pool_id)
        ? globalThis.Number(object.pool_id)
        : 0,
      amountA: isSet(object.amountA)
        ? Coin.fromJSON(object.amountA)
        : isSet(object.amount_a)
        ? Coin.fromJSON(object.amount_a)
        : undefined,
      amountB: isSet(object.amountB)
        ? Coin.fromJSON(object.amountB)
        : isSet(object.amount_b)
        ? Coin.fromJSON(object.amount_b)
        : undefined,
    };
  },

  toJSON(message: MsgAddLiquidity): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.poolId !== 0) {
      obj.poolId = Math.round(message.poolId);
    }
    if (message.amountA !== undefined) {
      obj.amountA = Coin.toJSON(message.amountA);
    }
    if (message.amountB !== undefined) {
      obj.amountB = Coin.toJSON(message.amountB);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAddLiquidity>, I>>(base?: I): MsgAddLiquidity {
    return MsgAddLiquidity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAddLiquidity>, I>>(object: I): MsgAddLiquidity {
    const message = createBaseMsgAddLiquidity();
    message.creator = object.creator ?? "";
    message.poolId = object.poolId ?? 0;
    message.amountA = (object.amountA !== undefined && object.amountA !== null)
      ? Coin.fromPartial(object.amountA)
      : undefined;
    message.amountB = (object.amountB !== undefined && object.amountB !== null)
      ? Coin.fromPartial(object.amountB)
      : undefined;
    return message;
  },
};

function createBaseMsgAddLiquidityResponse(): MsgAddLiquidityResponse {
  return { shares: undefined };
}

export const MsgAddLiquidityResponse: MessageFns<MsgAddLiquidityResponse> = {
  encode(message: MsgAddLiquidityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.shares !== undefined) {
      Coin.encode(message.shares, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAddLiquidityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAddLiquidityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.shares = Coin.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgAddLiquidityResponse {
    return { shares: isSet(object.shares) ? Coin.fromJSON(object.shares) : undefined };
  },

  toJSON(message: MsgAddLiquidityResponse): unknown {
    const obj: any = {};
    if (message.shares !== undefined) {
      obj.shares = Coin.toJSON(message.shares);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAddLiquidityResponse>, I>>(base?: I): MsgAddLiquidityResponse {
    return MsgAddLiquidityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAddLiquidityResponse>, I>>(object: I): MsgAddLiquidityResponse {
    const message = createBaseMsgAddLiquidityResponse();
    message.shares = (object.shares !== undefined && object.shares !== null)
      ? Coin.fromPartial(object.shares)
      : undefined;
    return message;
  },
};

function createBaseMsgRemoveLiquidity(): MsgRemoveLiquidity {
  return { creator: "", poolId: 0, shares: undefined };
}

export const MsgRemoveLiquidity: MessageFns<MsgRemoveLiquidity> = {
  encode(message: MsgRemoveLiquidity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.poolId !== 0) {
      writer.uint32(16).uint64(message.poolId);
    }
    if (message.shares !== undefined) {
      Coin.encode(message.shares, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRemoveLiquidity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRemoveLiquidity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.poolId = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.shares = Coin.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRemoveLiquidity {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      poolId: isSet(object.poolId)
        ? globalThis.Number(object.poolId)
        : isSet(object.pool_id)
        ? globalThis.Number(object.pool_id)
        : 0,
      shares: isSet(object.shares) ? Coin.fromJSON(object.shares) : undefined,
    };
  },

  toJSON(message: MsgRemoveLiquidity): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.poolId !== 0) {
      obj.poolId = Math.round(message.poolId);
    }
    if (message.shares !== undefined) {
      obj.shares = Coin.toJSON(message.shares);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRemoveLiquidity>, I>>(base?: I): MsgRemoveLiquidity {
    return MsgRemoveLiquidity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRemoveLiquidity>, I>>(object: I): MsgRemoveLiquidity {
    const message = createBaseMsgRemoveLiquidity();
    message.creator = object.creator ?? "";
    message.poolId = object.poolId ?? 0;
    message.shares = (object.shares !== undefined && object.shares !== null)
      ? Coin.fromPartial(object.shares)
      : undefined;
    return message;
  },
};

function createBaseMsgRemoveLiquidityResponse(): MsgRemoveLiquidityResponse {
  return { completionTime: 0 };
}

export const MsgRemoveLiquidityResponse: MessageFns<MsgRemoveLiquidityResponse> = {
  encode(message: MsgRemoveLiquidityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.completionTime !== 0) {
      writer.uint32(8).int64(message.completionTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRemoveLiquidityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRemoveLiquidityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.completionTime = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRemoveLiquidityResponse {
    return {
      completionTime: isSet(object.completionTime)
        ? globalThis.Number(object.completionTime)
        : isSet(object.completion_time)
        ? globalThis.Number(object.completion_time)
        : 0,
    };
  },

  toJSON(message: MsgRemoveLiquidityResponse): unknown {
    const obj: any = {};
    if (message.completionTime !== 0) {
      obj.completionTime = Math.round(message.completionTime);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRemoveLiquidityResponse>, I>>(base?: I): MsgRemoveLiquidityResponse {
    return MsgRemoveLiquidityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRemoveLiquidityResponse>, I>>(object: I): MsgRemoveLiquidityResponse {
    const message = createBaseMsgRemoveLiquidityResponse();
    message.completionTime = object.completionTime ?? 0;
    return message;
  },
};

function createBaseMsgSwap(): MsgSwap {
  return { creator: "", tokenIn: undefined, denomOut: "", minAmountOut: "" };
}

export const MsgSwap: MessageFns<MsgSwap> = {
  encode(message: MsgSwap, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.tokenIn !== undefined) {
      Coin.encode(message.tokenIn, writer.uint32(18).fork()).join();
    }
    if (message.denomOut !== "") {
      writer.uint32(26).string(message.denomOut);
    }
    if (message.minAmountOut !== "") {
      writer.uint32(34).string(message.minAmountOut);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSwap {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSwap();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tokenIn = Coin.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.denomOut = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.minAmountOut = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSwap {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      tokenIn: isSet(object.tokenIn)
        ? Coin.fromJSON(object.tokenIn)
        : isSet(object.token_in)
        ? Coin.fromJSON(object.token_in)
        : undefined,
      denomOut: isSet(object.denomOut)
        ? globalThis.String(object.denomOut)
        : isSet(object.denom_out)
        ? globalThis.String(object.denom_out)
        : "",
      minAmountOut: isSet(object.minAmountOut)
        ? globalThis.String(object.minAmountOut)
        : isSet(object.min_amount_out)
        ? globalThis.String(object.min_amount_out)
        : "",
    };
  },

  toJSON(message: MsgSwap): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.tokenIn !== undefined) {
      obj.tokenIn = Coin.toJSON(message.tokenIn);
    }
    if (message.denomOut !== "") {
      obj.denomOut = message.denomOut;
    }
    if (message.minAmountOut !== "") {
      obj.minAmountOut = message.minAmountOut;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSwap>, I>>(base?: I): MsgSwap {
    return MsgSwap.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSwap>, I>>(object: I): MsgSwap {
    const message = createBaseMsgSwap();
    message.creator = object.creator ?? "";
    message.tokenIn = (object.tokenIn !== undefined && object.tokenIn !== null)
      ? Coin.fromPartial(object.tokenIn)
      : undefined;
    message.denomOut = object.denomOut ?? "";
    message.minAmountOut = object.minAmountOut ?? "";
    return message;
  },
};

function createBaseMsgSwapResponse(): MsgSwapResponse {
  return { tokenOut: undefined };
}

export const MsgSwapResponse: MessageFns<MsgSwapResponse> = {
  encode(message: MsgSwapResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tokenOut !== undefined) {
      Coin.encode(message.tokenOut, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSwapResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSwapResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tokenOut = Coin.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSwapResponse {
    return {
      tokenOut: isSet(object.tokenOut)
        ? Coin.fromJSON(object.tokenOut)
        : isSet(object.token_out)
        ? Coin.fromJSON(object.token_out)
        : undefined,
    };
  },

  toJSON(message: MsgSwapResponse): unknown {
    const obj: any = {};
    if (message.tokenOut !== undefined) {
      obj.tokenOut = Coin.toJSON(message.tokenOut);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSwapResponse>, I>>(base?: I): MsgSwapResponse {
    return MsgSwapResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSwapResponse>, I>>(object: I): MsgSwapResponse {
    const message = createBaseMsgSwapResponse();
    message.tokenOut = (object.tokenOut !== undefined && object.tokenOut !== null)
      ? Coin.fromPartial(object.tokenOut)
      : undefined;
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** CreatePool defines the CreatePool RPC. */
  CreatePool(request: MsgCreatePool): Promise<MsgCreatePoolResponse>;
  /** AddLiquidity defines the AddLiquidity RPC. */
  AddLiquidity(request: MsgAddLiquidity): Promise<MsgAddLiquidityResponse>;
  /**
   * RemoveLiquidity begins a liquidity withdrawal. It does not pay out: the
   * shares are escrowed for the unbonding period and then swept to the
   * provider's wallet automatically, with no second transaction.
   */
  RemoveLiquidity(request: MsgRemoveLiquidity): Promise<MsgRemoveLiquidityResponse>;
  /** Swap defines the Swap RPC. */
  Swap(request: MsgSwap): Promise<MsgSwapResponse>;
}

export const MsgServiceName = "earth.dex.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.CreatePool = this.CreatePool.bind(this);
    this.AddLiquidity = this.AddLiquidity.bind(this);
    this.RemoveLiquidity = this.RemoveLiquidity.bind(this);
    this.Swap = this.Swap.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  CreatePool(request: MsgCreatePool): Promise<MsgCreatePoolResponse> {
    const data = MsgCreatePool.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreatePool", data);
    return promise.then((data) => MsgCreatePoolResponse.decode(new BinaryReader(data)));
  }

  AddLiquidity(request: MsgAddLiquidity): Promise<MsgAddLiquidityResponse> {
    const data = MsgAddLiquidity.encode(request).finish();
    const promise = this.rpc.request(this.service, "AddLiquidity", data);
    return promise.then((data) => MsgAddLiquidityResponse.decode(new BinaryReader(data)));
  }

  RemoveLiquidity(request: MsgRemoveLiquidity): Promise<MsgRemoveLiquidityResponse> {
    const data = MsgRemoveLiquidity.encode(request).finish();
    const promise = this.rpc.request(this.service, "RemoveLiquidity", data);
    return promise.then((data) => MsgRemoveLiquidityResponse.decode(new BinaryReader(data)));
  }

  Swap(request: MsgSwap): Promise<MsgSwapResponse> {
    const data = MsgSwap.encode(request).finish();
    const promise = this.rpc.request(this.service, "Swap", data);
    return promise.then((data) => MsgSwapResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
