// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: earth/assembly/v1/assembly.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "earth.assembly.v1";

/**
 * VoteOption is one human's position on a ballot.
 *
 * There is deliberately no abstain. Approval is two thirds of the votes cast, so
 * an abstention and a non-vote come to exactly the same arithmetic; offering
 * both would only invite a voter to think they had done something different.
 */
export enum VoteOption {
  /** VOTE_OPTION_UNSPECIFIED - VOTE_OPTION_UNSPECIFIED is an invalid default; every vote must name a side. */
  VOTE_OPTION_UNSPECIFIED = 0,
  VOTE_OPTION_YES = 1,
  VOTE_OPTION_NO = 2,
  UNRECOGNIZED = -1,
}

export function voteOptionFromJSON(object: any): VoteOption {
  switch (object) {
    case 0:
    case "VOTE_OPTION_UNSPECIFIED":
      return VoteOption.VOTE_OPTION_UNSPECIFIED;
    case 1:
    case "VOTE_OPTION_YES":
      return VoteOption.VOTE_OPTION_YES;
    case 2:
    case "VOTE_OPTION_NO":
      return VoteOption.VOTE_OPTION_NO;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VoteOption.UNRECOGNIZED;
  }
}

export function voteOptionToJSON(object: VoteOption): string {
  switch (object) {
    case VoteOption.VOTE_OPTION_UNSPECIFIED:
      return "VOTE_OPTION_UNSPECIFIED";
    case VoteOption.VOTE_OPTION_YES:
      return "VOTE_OPTION_YES";
    case VoteOption.VOTE_OPTION_NO:
      return "VOTE_OPTION_NO";
    case VoteOption.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * Tally is a ballot's running count. Votes are people, not weight: the whole
 * point of this chamber is that there is no number attached to a human.
 */
export interface Tally {
  yes: number;
  no: number;
}

/**
 * RemovalBallot is an open vote to remove one groundworks allocation option.
 *
 * The stream is not recorded because there is only one it can be. Removal is the
 * chamber's single affirmative power and it reaches the groundworks slate alone;
 * the caretaker slate is directed by these same humans voting continuously, and
 * has no need of a second instrument pointed at it.
 */
export interface RemovalBallot {
  optionId: number;
  /**
   * closes_at is when voting ends, in unix seconds. The EndBlocker resolves the
   * ballot at the first block at or after it.
   */
  closesAt: number;
  tally:
    | Tally
    | undefined;
  /**
   * opened_at is when the ballot opened, in unix seconds. Membership proofs
   * for it must come from identities activated at least an identity root
   * window before.
   */
  openedAt: number;
  /** ballot_id is the ballot's id, which its scope is derived from. */
  ballotId: number;
}

/**
 * ProposalRound is a proposal's current round of human voting when it is not
 * the first: after the chamber demotes an expedited proposal, the regular
 * round is a new ballot with its own scope and opening time.
 */
export interface ProposalRound {
  round: number;
  openedAt: number;
}

/**
 * ProposalSubjects is who a proposal is about, fixed when it enters voting:
 * the registrations its revocations would remove, which may not vote on it.
 * Exactly one of excluded_dsc / excluded_country is set, or neither, or
 * refusal says why the proposal cannot be voted on. See x/assembly
 * keeper/subjects.go.
 */
export interface ProposalSubjects {
  /**
   * excluded_dsc is the one Document Signer (Poseidon2 commitment) the
   * proposal revokes, when that is all it revokes.
   */
  excludedDsc: Uint8Array;
  /**
   * excluded_country is the ISO 3166-1 alpha-2 code of the one country every
   * revocation in the proposal belongs to.
   */
  excludedCountry: string;
  /**
   * refusal is set when the subjects cannot be excluded with one proof (they
   * span countries, or one is of unknown country among several): no vote can
   * be cast and the proposal must be split.
   */
  refusal: string;
}

function createBaseTally(): Tally {
  return { yes: 0, no: 0 };
}

export const Tally: MessageFns<Tally> = {
  encode(message: Tally, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.yes !== 0) {
      writer.uint32(8).uint64(message.yes);
    }
    if (message.no !== 0) {
      writer.uint32(16).uint64(message.no);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Tally {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTally();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.yes = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.no = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Tally {
    return {
      yes: isSet(object.yes) ? globalThis.Number(object.yes) : 0,
      no: isSet(object.no) ? globalThis.Number(object.no) : 0,
    };
  },

  toJSON(message: Tally): unknown {
    const obj: any = {};
    if (message.yes !== 0) {
      obj.yes = Math.round(message.yes);
    }
    if (message.no !== 0) {
      obj.no = Math.round(message.no);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Tally>, I>>(base?: I): Tally {
    return Tally.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Tally>, I>>(object: I): Tally {
    const message = createBaseTally();
    message.yes = object.yes ?? 0;
    message.no = object.no ?? 0;
    return message;
  },
};

function createBaseRemovalBallot(): RemovalBallot {
  return { optionId: 0, closesAt: 0, tally: undefined, openedAt: 0, ballotId: 0 };
}

export const RemovalBallot: MessageFns<RemovalBallot> = {
  encode(message: RemovalBallot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.optionId !== 0) {
      writer.uint32(8).uint64(message.optionId);
    }
    if (message.closesAt !== 0) {
      writer.uint32(24).int64(message.closesAt);
    }
    if (message.tally !== undefined) {
      Tally.encode(message.tally, writer.uint32(34).fork()).join();
    }
    if (message.openedAt !== 0) {
      writer.uint32(40).int64(message.openedAt);
    }
    if (message.ballotId !== 0) {
      writer.uint32(48).uint64(message.ballotId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemovalBallot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRemovalBallot();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.optionId = longToNumber(reader.uint64());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.closesAt = longToNumber(reader.int64());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.tally = Tally.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.openedAt = longToNumber(reader.int64());
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.ballotId = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): RemovalBallot {
    return {
      optionId: isSet(object.optionId)
        ? globalThis.Number(object.optionId)
        : isSet(object.option_id)
        ? globalThis.Number(object.option_id)
        : 0,
      closesAt: isSet(object.closesAt)
        ? globalThis.Number(object.closesAt)
        : isSet(object.closes_at)
        ? globalThis.Number(object.closes_at)
        : 0,
      tally: isSet(object.tally) ? Tally.fromJSON(object.tally) : undefined,
      openedAt: isSet(object.openedAt)
        ? globalThis.Number(object.openedAt)
        : isSet(object.opened_at)
        ? globalThis.Number(object.opened_at)
        : 0,
      ballotId: isSet(object.ballotId)
        ? globalThis.Number(object.ballotId)
        : isSet(object.ballot_id)
        ? globalThis.Number(object.ballot_id)
        : 0,
    };
  },

  toJSON(message: RemovalBallot): unknown {
    const obj: any = {};
    if (message.optionId !== 0) {
      obj.optionId = Math.round(message.optionId);
    }
    if (message.closesAt !== 0) {
      obj.closesAt = Math.round(message.closesAt);
    }
    if (message.tally !== undefined) {
      obj.tally = Tally.toJSON(message.tally);
    }
    if (message.openedAt !== 0) {
      obj.openedAt = Math.round(message.openedAt);
    }
    if (message.ballotId !== 0) {
      obj.ballotId = Math.round(message.ballotId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RemovalBallot>, I>>(base?: I): RemovalBallot {
    return RemovalBallot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RemovalBallot>, I>>(object: I): RemovalBallot {
    const message = createBaseRemovalBallot();
    message.optionId = object.optionId ?? 0;
    message.closesAt = object.closesAt ?? 0;
    message.tally = (object.tally !== undefined && object.tally !== null) ? Tally.fromPartial(object.tally) : undefined;
    message.openedAt = object.openedAt ?? 0;
    message.ballotId = object.ballotId ?? 0;
    return message;
  },
};

function createBaseProposalRound(): ProposalRound {
  return { round: 0, openedAt: 0 };
}

export const ProposalRound: MessageFns<ProposalRound> = {
  encode(message: ProposalRound, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.round !== 0) {
      writer.uint32(8).uint64(message.round);
    }
    if (message.openedAt !== 0) {
      writer.uint32(16).int64(message.openedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProposalRound {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProposalRound();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.round = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.openedAt = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ProposalRound {
    return {
      round: isSet(object.round) ? globalThis.Number(object.round) : 0,
      openedAt: isSet(object.openedAt)
        ? globalThis.Number(object.openedAt)
        : isSet(object.opened_at)
        ? globalThis.Number(object.opened_at)
        : 0,
    };
  },

  toJSON(message: ProposalRound): unknown {
    const obj: any = {};
    if (message.round !== 0) {
      obj.round = Math.round(message.round);
    }
    if (message.openedAt !== 0) {
      obj.openedAt = Math.round(message.openedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProposalRound>, I>>(base?: I): ProposalRound {
    return ProposalRound.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProposalRound>, I>>(object: I): ProposalRound {
    const message = createBaseProposalRound();
    message.round = object.round ?? 0;
    message.openedAt = object.openedAt ?? 0;
    return message;
  },
};

function createBaseProposalSubjects(): ProposalSubjects {
  return { excludedDsc: new Uint8Array(0), excludedCountry: "", refusal: "" };
}

export const ProposalSubjects: MessageFns<ProposalSubjects> = {
  encode(message: ProposalSubjects, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.excludedDsc.length !== 0) {
      writer.uint32(10).bytes(message.excludedDsc);
    }
    if (message.excludedCountry !== "") {
      writer.uint32(18).string(message.excludedCountry);
    }
    if (message.refusal !== "") {
      writer.uint32(26).string(message.refusal);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProposalSubjects {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseProposalSubjects();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.excludedDsc = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.excludedCountry = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.refusal = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ProposalSubjects {
    return {
      excludedDsc: isSet(object.excludedDsc)
        ? bytesFromBase64(object.excludedDsc)
        : isSet(object.excluded_dsc)
        ? bytesFromBase64(object.excluded_dsc)
        : new Uint8Array(0),
      excludedCountry: isSet(object.excludedCountry)
        ? globalThis.String(object.excludedCountry)
        : isSet(object.excluded_country)
        ? globalThis.String(object.excluded_country)
        : "",
      refusal: isSet(object.refusal) ? globalThis.String(object.refusal) : "",
    };
  },

  toJSON(message: ProposalSubjects): unknown {
    const obj: any = {};
    if (message.excludedDsc.length !== 0) {
      obj.excludedDsc = base64FromBytes(message.excludedDsc);
    }
    if (message.excludedCountry !== "") {
      obj.excludedCountry = message.excludedCountry;
    }
    if (message.refusal !== "") {
      obj.refusal = message.refusal;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProposalSubjects>, I>>(base?: I): ProposalSubjects {
    return ProposalSubjects.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProposalSubjects>, I>>(object: I): ProposalSubjects {
    const message = createBaseProposalSubjects();
    message.excludedDsc = object.excludedDsc ?? new Uint8Array(0);
    message.excludedCountry = object.excludedCountry ?? "";
    message.refusal = object.refusal ?? "";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
