// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: earth/personhood/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "earth.personhood.v1";

/** Params defines the parameters for the module. */
export interface Params {
  /**
   * verifying_keys maps a passport document/circuit id to the Barretenberg
   * UltraHonk (bb v5.0.0) verifying-key blob for that register circuit. The prover
   * (phone) picks the circuit matching its passport; the chain selects the key by
   * the same id. Governance manages the set. Empty disables registration until
   * keys are configured.
   */
  verifyingKeys: { [key: string]: Uint8Array };
  /**
   * registration_validity_seconds is how long a registration stays valid before
   * it must be renewed.
   */
  registrationValiditySeconds: number;
  /**
   * nullifier_index is the public-input position of the nullifier
   * (zkPassport's scoped_nullifier) in the register circuit's public inputs.
   */
  nullifierIndex: number;
  /**
   * dsc_key_index is the public-input position of the DSC commitment —
   * Poseidon2 over the Document Signer's canonical public key. The chain
   * recomputes it from the certificate in MsgRegister and requires equality,
   * which is what binds the proof to a specific, CSCA-verified signer.
   */
  dscKeyIndex: number;
  /**
   * current_date_index is the public-input position of the prover-supplied
   * current_date (YYMMDD) in the register circuit's public inputs. The circuit
   * proves the passport expiry >= current_date; the chain pins current_date to
   * block time (see current_date_max_skew_seconds) so an expired passport
   * cannot be registered by backdating current_date.
   */
  currentDateIndex: number;
  /**
   * current_date_max_skew_seconds bounds how far the proof's current_date may
   * differ from the block time.
   *
   * Zero is rejected by Params.Validate and disables registration outright. It
   * is not "no tolerance": the skew comparison is the only thing tying the
   * prover-supplied current_date to real time, so skipping it lets any expired
   * passport prove out against a backdated date.
   */
  currentDateMaxSkewSeconds: number;
  /**
   * expiry_sweep_limit caps how many lapsed registrations BeginBlocker retires
   * per block, bounding the work a cohort that all registered together can land
   * on a single block. Exceeding it is safe — the backlog drains over following
   * blocks and emits registration_sweep_capped — so this is the dial to raise if
   * that event persists. Zero falls back to the compiled-in default.
   */
  expirySweepLimit: number;
}

export interface Params_VerifyingKeysEntry {
  key: string;
  value: Uint8Array;
}

function createBaseParams(): Params {
  return {
    verifyingKeys: {},
    registrationValiditySeconds: 0,
    nullifierIndex: 0,
    dscKeyIndex: 0,
    currentDateIndex: 0,
    currentDateMaxSkewSeconds: 0,
    expirySweepLimit: 0,
  };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.verifyingKeys).forEach(([key, value]: [string, Uint8Array]) => {
      Params_VerifyingKeysEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    if (message.registrationValiditySeconds !== 0) {
      writer.uint32(24).uint64(message.registrationValiditySeconds);
    }
    if (message.nullifierIndex !== 0) {
      writer.uint32(32).uint32(message.nullifierIndex);
    }
    if (message.dscKeyIndex !== 0) {
      writer.uint32(40).uint32(message.dscKeyIndex);
    }
    if (message.currentDateIndex !== 0) {
      writer.uint32(48).uint32(message.currentDateIndex);
    }
    if (message.currentDateMaxSkewSeconds !== 0) {
      writer.uint32(56).uint64(message.currentDateMaxSkewSeconds);
    }
    if (message.expirySweepLimit !== 0) {
      writer.uint32(72).uint64(message.expirySweepLimit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = Params_VerifyingKeysEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.verifyingKeys[entry1.key] = entry1.value;
          }
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.registrationValiditySeconds = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.nullifierIndex = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dscKeyIndex = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.currentDateIndex = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.currentDateMaxSkewSeconds = longToNumber(reader.uint64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.expirySweepLimit = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      verifyingKeys: isObject(object.verifyingKeys)
        ? (globalThis.Object.entries(object.verifyingKeys) as [string, any][]).reduce(
          (acc: { [key: string]: Uint8Array }, [key, value]: [string, any]) => {
            acc[key] = bytesFromBase64(value as string);
            return acc;
          },
          {},
        )
        : isObject(object.verifying_keys)
        ? (globalThis.Object.entries(object.verifying_keys) as [string, any][]).reduce(
          (acc: { [key: string]: Uint8Array }, [key, value]: [string, any]) => {
            acc[key] = bytesFromBase64(value as string);
            return acc;
          },
          {},
        )
        : {},
      registrationValiditySeconds: isSet(object.registrationValiditySeconds)
        ? globalThis.Number(object.registrationValiditySeconds)
        : isSet(object.registration_validity_seconds)
        ? globalThis.Number(object.registration_validity_seconds)
        : 0,
      nullifierIndex: isSet(object.nullifierIndex)
        ? globalThis.Number(object.nullifierIndex)
        : isSet(object.nullifier_index)
        ? globalThis.Number(object.nullifier_index)
        : 0,
      dscKeyIndex: isSet(object.dscKeyIndex)
        ? globalThis.Number(object.dscKeyIndex)
        : isSet(object.dsc_key_index)
        ? globalThis.Number(object.dsc_key_index)
        : 0,
      currentDateIndex: isSet(object.currentDateIndex)
        ? globalThis.Number(object.currentDateIndex)
        : isSet(object.current_date_index)
        ? globalThis.Number(object.current_date_index)
        : 0,
      currentDateMaxSkewSeconds: isSet(object.currentDateMaxSkewSeconds)
        ? globalThis.Number(object.currentDateMaxSkewSeconds)
        : isSet(object.current_date_max_skew_seconds)
        ? globalThis.Number(object.current_date_max_skew_seconds)
        : 0,
      expirySweepLimit: isSet(object.expirySweepLimit)
        ? globalThis.Number(object.expirySweepLimit)
        : isSet(object.expiry_sweep_limit)
        ? globalThis.Number(object.expiry_sweep_limit)
        : 0,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.verifyingKeys) {
      const entries = globalThis.Object.entries(message.verifyingKeys) as [string, Uint8Array][];
      if (entries.length > 0) {
        obj.verifyingKeys = {};
        entries.forEach(([k, v]) => {
          obj.verifyingKeys[k] = base64FromBytes(v);
        });
      }
    }
    if (message.registrationValiditySeconds !== 0) {
      obj.registrationValiditySeconds = Math.round(message.registrationValiditySeconds);
    }
    if (message.nullifierIndex !== 0) {
      obj.nullifierIndex = Math.round(message.nullifierIndex);
    }
    if (message.dscKeyIndex !== 0) {
      obj.dscKeyIndex = Math.round(message.dscKeyIndex);
    }
    if (message.currentDateIndex !== 0) {
      obj.currentDateIndex = Math.round(message.currentDateIndex);
    }
    if (message.currentDateMaxSkewSeconds !== 0) {
      obj.currentDateMaxSkewSeconds = Math.round(message.currentDateMaxSkewSeconds);
    }
    if (message.expirySweepLimit !== 0) {
      obj.expirySweepLimit = Math.round(message.expirySweepLimit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.verifyingKeys = (globalThis.Object.entries(object.verifyingKeys ?? {}) as [string, Uint8Array][]).reduce(
      (acc: { [key: string]: Uint8Array }, [key, value]: [string, Uint8Array]) => {
        if (value !== undefined) {
          acc[key] = value;
        }
        return acc;
      },
      {},
    );
    message.registrationValiditySeconds = object.registrationValiditySeconds ?? 0;
    message.nullifierIndex = object.nullifierIndex ?? 0;
    message.dscKeyIndex = object.dscKeyIndex ?? 0;
    message.currentDateIndex = object.currentDateIndex ?? 0;
    message.currentDateMaxSkewSeconds = object.currentDateMaxSkewSeconds ?? 0;
    message.expirySweepLimit = object.expirySweepLimit ?? 0;
    return message;
  },
};

function createBaseParams_VerifyingKeysEntry(): Params_VerifyingKeysEntry {
  return { key: "", value: new Uint8Array(0) };
}

export const Params_VerifyingKeysEntry: MessageFns<Params_VerifyingKeysEntry> = {
  encode(message: Params_VerifyingKeysEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value.length !== 0) {
      writer.uint32(18).bytes(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params_VerifyingKeysEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams_VerifyingKeysEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params_VerifyingKeysEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? bytesFromBase64(object.value) : new Uint8Array(0),
    };
  },

  toJSON(message: Params_VerifyingKeysEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value.length !== 0) {
      obj.value = base64FromBytes(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params_VerifyingKeysEntry>, I>>(base?: I): Params_VerifyingKeysEntry {
    return Params_VerifyingKeysEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params_VerifyingKeysEntry>, I>>(object: I): Params_VerifyingKeysEntry {
    const message = createBaseParams_VerifyingKeysEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? new Uint8Array(0);
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
