// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: earth/personhood/v1/registration.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "earth.personhood.v1";

/**
 * Registration is one registered passport: its dedup key, and where its
 * holder's identity sits in the identity tree. It names no account and no
 * note; nothing here links the passport to what its holder later does.
 */
export interface Registration {
  /**
   * nullifier is the passport nullifier the registration proof outputs, the
   * public dedup key. Derived from passport data (issuer, document number,
   * date of birth), so it identifies the passport to its issuer: that is why
   * nothing the holder does after registering is keyed by it.
   */
  nullifier: Uint8Array;
  /**
   * leaf_index is the identity tree position of this registration's leaf
   * H(TAG_LEAF, idc, dsc_key, country, activated_at). Zeroed when the registration
   * expires, its signer is revoked, or its holder switches.
   */
  leafIndex: number;
  /**
   * registered_at is the unix time (seconds) of the registration; it expires
   * registration_validity_seconds later.
   */
  registeredAt: number;
  /**
   * activated_at is the unix time the leaf was written, which the leaf
   * commits to. Membership proofs bound it from above (see Params) so a
   * switch to a new identity secret cannot act again where the old one did.
   */
  activatedAt: number;
  /**
   * dsc_key is the Poseidon2 commitment to the Document Signer that produced
   * the registration proof, which the leaf also commits to.
   */
  dscKey: Uint8Array;
  /**
   * country is the ISO 3166-1 alpha-2 of the CSCA that verified the DSC, or
   * "" when it names none. The leaf commits to zk/privacy.CountryField of it
   * (0 for unknown), so an assembly vote can exclude a country's
   * registrations.
   */
  country: string;
  /**
   * idc is the identity commitment H(TAG_ID, id_secret) the leaf was made
   * from. Public in MsgRegister already; kept so genesis can rebuild the tree.
   */
  idc: Uint8Array;
}

/**
 * RateCounter is a self-resetting daily counter, used to bound how many
 * registrations one Document Signer or one issuing country may produce in a day.
 *
 * Stored as a (day, count) pair rather than as a row per day so it costs one
 * entry per subject no matter how long the chain runs: when the day rolls the
 * count resets in place, and there is nothing to prune. The cost of that is
 * that history is not kept — only the current day, and the one before it.
 */
export interface RateCounter {
  /** day is the unix day (block time / 86400) the count belongs to. */
  day: number;
  /** count is how many registrations have landed during that day. */
  count: number;
  /**
   * previous_count is the completed previous day's total.
   *
   * Only the network-wide counter uses it, and it is what the per-signer caps
   * scale against. Scaling against the current day instead would be circular:
   * the day starts at zero, so every cap would start the day at its floor and
   * widen as registrations arrived — tightest exactly when a burst begins.
   */
  previousCount: number;
}

/**
 * IdentityRoot is one recorded identity-tree root. A root becomes a valid
 * anchor for membership proofs at the end of the block that produced it and
 * stays one for identity_root_window_seconds (the latest root always).
 */
export interface IdentityRoot {
  root: Uint8Array;
  height: number;
  time: number;
  treeSize: number;
}

/**
 * Membership is an anonymous proof that its prover holds a live identity-tree
 * leaf (membership circuit, bb v5.0.0 UltraHonk). The chain supplies the other
 * public inputs itself: scope, signal, excluded_dsc, excluded_country and
 * max_activation are fixed by the msg carrying it.
 */
export interface Membership {
  proof: Uint8Array;
  /** root is the identity-tree anchor the proof was made against. */
  root: Uint8Array;
  /** nullifier is H(TAG_SN, id_secret, scope): one per person per scope. */
  nullifier: Uint8Array;
}

/** ClaimNullifier records that the holder of nullifier claimed on day. */
export interface ClaimNullifier {
  day: number;
  nullifier: Uint8Array;
}

/**
 * CaretakerVote is a live caretaker split's lease: the split itself is the
 * x/allocation voter filed under the same nullifier.
 */
export interface CaretakerVote {
  nullifier: Uint8Array;
  expiresAt: number;
}

/**
 * ReferrerBinding is a live referral address: registrations naming address
 * pay the referrer's half there until expires_at. Keyed by the binder's
 * referrer-scope nullifier, which says nothing about who bound it.
 */
export interface ReferrerBinding {
  nullifier: Uint8Array;
  address: string;
  expiresAt: number;
}

function createBaseRegistration(): Registration {
  return {
    nullifier: new Uint8Array(0),
    leafIndex: 0,
    registeredAt: 0,
    activatedAt: 0,
    dscKey: new Uint8Array(0),
    country: "",
    idc: new Uint8Array(0),
  };
}

export const Registration: MessageFns<Registration> = {
  encode(message: Registration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nullifier.length !== 0) {
      writer.uint32(10).bytes(message.nullifier);
    }
    if (message.leafIndex !== 0) {
      writer.uint32(16).uint64(message.leafIndex);
    }
    if (message.registeredAt !== 0) {
      writer.uint32(24).int64(message.registeredAt);
    }
    if (message.activatedAt !== 0) {
      writer.uint32(32).int64(message.activatedAt);
    }
    if (message.dscKey.length !== 0) {
      writer.uint32(42).bytes(message.dscKey);
    }
    if (message.country !== "") {
      writer.uint32(50).string(message.country);
    }
    if (message.idc.length !== 0) {
      writer.uint32(58).bytes(message.idc);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Registration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRegistration();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.nullifier = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.leafIndex = longToNumber(reader.uint64());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.registeredAt = longToNumber(reader.int64());
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.activatedAt = longToNumber(reader.int64());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.dscKey = reader.bytes();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.country = reader.string();
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.idc = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Registration {
    return {
      nullifier: isSet(object.nullifier) ? bytesFromBase64(object.nullifier) : new Uint8Array(0),
      leafIndex: isSet(object.leafIndex)
        ? globalThis.Number(object.leafIndex)
        : isSet(object.leaf_index)
        ? globalThis.Number(object.leaf_index)
        : 0,
      registeredAt: isSet(object.registeredAt)
        ? globalThis.Number(object.registeredAt)
        : isSet(object.registered_at)
        ? globalThis.Number(object.registered_at)
        : 0,
      activatedAt: isSet(object.activatedAt)
        ? globalThis.Number(object.activatedAt)
        : isSet(object.activated_at)
        ? globalThis.Number(object.activated_at)
        : 0,
      dscKey: isSet(object.dscKey)
        ? bytesFromBase64(object.dscKey)
        : isSet(object.dsc_key)
        ? bytesFromBase64(object.dsc_key)
        : new Uint8Array(0),
      country: isSet(object.country) ? globalThis.String(object.country) : "",
      idc: isSet(object.idc) ? bytesFromBase64(object.idc) : new Uint8Array(0),
    };
  },

  toJSON(message: Registration): unknown {
    const obj: any = {};
    if (message.nullifier.length !== 0) {
      obj.nullifier = base64FromBytes(message.nullifier);
    }
    if (message.leafIndex !== 0) {
      obj.leafIndex = Math.round(message.leafIndex);
    }
    if (message.registeredAt !== 0) {
      obj.registeredAt = Math.round(message.registeredAt);
    }
    if (message.activatedAt !== 0) {
      obj.activatedAt = Math.round(message.activatedAt);
    }
    if (message.dscKey.length !== 0) {
      obj.dscKey = base64FromBytes(message.dscKey);
    }
    if (message.country !== "") {
      obj.country = message.country;
    }
    if (message.idc.length !== 0) {
      obj.idc = base64FromBytes(message.idc);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Registration>, I>>(base?: I): Registration {
    return Registration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Registration>, I>>(object: I): Registration {
    const message = createBaseRegistration();
    message.nullifier = object.nullifier ?? new Uint8Array(0);
    message.leafIndex = object.leafIndex ?? 0;
    message.registeredAt = object.registeredAt ?? 0;
    message.activatedAt = object.activatedAt ?? 0;
    message.dscKey = object.dscKey ?? new Uint8Array(0);
    message.country = object.country ?? "";
    message.idc = object.idc ?? new Uint8Array(0);
    return message;
  },
};

function createBaseRateCounter(): RateCounter {
  return { day: 0, count: 0, previousCount: 0 };
}

export const RateCounter: MessageFns<RateCounter> = {
  encode(message: RateCounter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.day !== 0) {
      writer.uint32(8).uint64(message.day);
    }
    if (message.count !== 0) {
      writer.uint32(16).uint64(message.count);
    }
    if (message.previousCount !== 0) {
      writer.uint32(24).uint64(message.previousCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RateCounter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRateCounter();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.day = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.count = longToNumber(reader.uint64());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.previousCount = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): RateCounter {
    return {
      day: isSet(object.day) ? globalThis.Number(object.day) : 0,
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
      previousCount: isSet(object.previousCount)
        ? globalThis.Number(object.previousCount)
        : isSet(object.previous_count)
        ? globalThis.Number(object.previous_count)
        : 0,
    };
  },

  toJSON(message: RateCounter): unknown {
    const obj: any = {};
    if (message.day !== 0) {
      obj.day = Math.round(message.day);
    }
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    if (message.previousCount !== 0) {
      obj.previousCount = Math.round(message.previousCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RateCounter>, I>>(base?: I): RateCounter {
    return RateCounter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RateCounter>, I>>(object: I): RateCounter {
    const message = createBaseRateCounter();
    message.day = object.day ?? 0;
    message.count = object.count ?? 0;
    message.previousCount = object.previousCount ?? 0;
    return message;
  },
};

function createBaseIdentityRoot(): IdentityRoot {
  return { root: new Uint8Array(0), height: 0, time: 0, treeSize: 0 };
}

export const IdentityRoot: MessageFns<IdentityRoot> = {
  encode(message: IdentityRoot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.root.length !== 0) {
      writer.uint32(10).bytes(message.root);
    }
    if (message.height !== 0) {
      writer.uint32(16).int64(message.height);
    }
    if (message.time !== 0) {
      writer.uint32(24).int64(message.time);
    }
    if (message.treeSize !== 0) {
      writer.uint32(32).uint64(message.treeSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IdentityRoot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseIdentityRoot();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.root = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.height = longToNumber(reader.int64());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.time = longToNumber(reader.int64());
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.treeSize = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): IdentityRoot {
    return {
      root: isSet(object.root) ? bytesFromBase64(object.root) : new Uint8Array(0),
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
      time: isSet(object.time) ? globalThis.Number(object.time) : 0,
      treeSize: isSet(object.treeSize)
        ? globalThis.Number(object.treeSize)
        : isSet(object.tree_size)
        ? globalThis.Number(object.tree_size)
        : 0,
    };
  },

  toJSON(message: IdentityRoot): unknown {
    const obj: any = {};
    if (message.root.length !== 0) {
      obj.root = base64FromBytes(message.root);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    if (message.time !== 0) {
      obj.time = Math.round(message.time);
    }
    if (message.treeSize !== 0) {
      obj.treeSize = Math.round(message.treeSize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IdentityRoot>, I>>(base?: I): IdentityRoot {
    return IdentityRoot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IdentityRoot>, I>>(object: I): IdentityRoot {
    const message = createBaseIdentityRoot();
    message.root = object.root ?? new Uint8Array(0);
    message.height = object.height ?? 0;
    message.time = object.time ?? 0;
    message.treeSize = object.treeSize ?? 0;
    return message;
  },
};

function createBaseMembership(): Membership {
  return { proof: new Uint8Array(0), root: new Uint8Array(0), nullifier: new Uint8Array(0) };
}

export const Membership: MessageFns<Membership> = {
  encode(message: Membership, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.proof.length !== 0) {
      writer.uint32(10).bytes(message.proof);
    }
    if (message.root.length !== 0) {
      writer.uint32(18).bytes(message.root);
    }
    if (message.nullifier.length !== 0) {
      writer.uint32(26).bytes(message.nullifier);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Membership {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMembership();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.proof = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.root = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.nullifier = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Membership {
    return {
      proof: isSet(object.proof) ? bytesFromBase64(object.proof) : new Uint8Array(0),
      root: isSet(object.root) ? bytesFromBase64(object.root) : new Uint8Array(0),
      nullifier: isSet(object.nullifier) ? bytesFromBase64(object.nullifier) : new Uint8Array(0),
    };
  },

  toJSON(message: Membership): unknown {
    const obj: any = {};
    if (message.proof.length !== 0) {
      obj.proof = base64FromBytes(message.proof);
    }
    if (message.root.length !== 0) {
      obj.root = base64FromBytes(message.root);
    }
    if (message.nullifier.length !== 0) {
      obj.nullifier = base64FromBytes(message.nullifier);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Membership>, I>>(base?: I): Membership {
    return Membership.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Membership>, I>>(object: I): Membership {
    const message = createBaseMembership();
    message.proof = object.proof ?? new Uint8Array(0);
    message.root = object.root ?? new Uint8Array(0);
    message.nullifier = object.nullifier ?? new Uint8Array(0);
    return message;
  },
};

function createBaseClaimNullifier(): ClaimNullifier {
  return { day: 0, nullifier: new Uint8Array(0) };
}

export const ClaimNullifier: MessageFns<ClaimNullifier> = {
  encode(message: ClaimNullifier, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.day !== 0) {
      writer.uint32(8).uint64(message.day);
    }
    if (message.nullifier.length !== 0) {
      writer.uint32(18).bytes(message.nullifier);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClaimNullifier {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseClaimNullifier();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.day = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.nullifier = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ClaimNullifier {
    return {
      day: isSet(object.day) ? globalThis.Number(object.day) : 0,
      nullifier: isSet(object.nullifier) ? bytesFromBase64(object.nullifier) : new Uint8Array(0),
    };
  },

  toJSON(message: ClaimNullifier): unknown {
    const obj: any = {};
    if (message.day !== 0) {
      obj.day = Math.round(message.day);
    }
    if (message.nullifier.length !== 0) {
      obj.nullifier = base64FromBytes(message.nullifier);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClaimNullifier>, I>>(base?: I): ClaimNullifier {
    return ClaimNullifier.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClaimNullifier>, I>>(object: I): ClaimNullifier {
    const message = createBaseClaimNullifier();
    message.day = object.day ?? 0;
    message.nullifier = object.nullifier ?? new Uint8Array(0);
    return message;
  },
};

function createBaseCaretakerVote(): CaretakerVote {
  return { nullifier: new Uint8Array(0), expiresAt: 0 };
}

export const CaretakerVote: MessageFns<CaretakerVote> = {
  encode(message: CaretakerVote, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nullifier.length !== 0) {
      writer.uint32(10).bytes(message.nullifier);
    }
    if (message.expiresAt !== 0) {
      writer.uint32(16).int64(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CaretakerVote {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCaretakerVote();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.nullifier = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.expiresAt = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): CaretakerVote {
    return {
      nullifier: isSet(object.nullifier) ? bytesFromBase64(object.nullifier) : new Uint8Array(0),
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
    };
  },

  toJSON(message: CaretakerVote): unknown {
    const obj: any = {};
    if (message.nullifier.length !== 0) {
      obj.nullifier = base64FromBytes(message.nullifier);
    }
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CaretakerVote>, I>>(base?: I): CaretakerVote {
    return CaretakerVote.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CaretakerVote>, I>>(object: I): CaretakerVote {
    const message = createBaseCaretakerVote();
    message.nullifier = object.nullifier ?? new Uint8Array(0);
    message.expiresAt = object.expiresAt ?? 0;
    return message;
  },
};

function createBaseReferrerBinding(): ReferrerBinding {
  return { nullifier: new Uint8Array(0), address: "", expiresAt: 0 };
}

export const ReferrerBinding: MessageFns<ReferrerBinding> = {
  encode(message: ReferrerBinding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nullifier.length !== 0) {
      writer.uint32(10).bytes(message.nullifier);
    }
    if (message.address !== "") {
      writer.uint32(18).string(message.address);
    }
    if (message.expiresAt !== 0) {
      writer.uint32(24).int64(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReferrerBinding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseReferrerBinding();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.nullifier = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.address = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.expiresAt = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ReferrerBinding {
    return {
      nullifier: isSet(object.nullifier) ? bytesFromBase64(object.nullifier) : new Uint8Array(0),
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
    };
  },

  toJSON(message: ReferrerBinding): unknown {
    const obj: any = {};
    if (message.nullifier.length !== 0) {
      obj.nullifier = base64FromBytes(message.nullifier);
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReferrerBinding>, I>>(base?: I): ReferrerBinding {
    return ReferrerBinding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReferrerBinding>, I>>(object: I): ReferrerBinding {
    const message = createBaseReferrerBinding();
    message.nullifier = object.nullifier ?? new Uint8Array(0);
    message.address = object.address ?? "";
    message.expiresAt = object.expiresAt ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
