// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: earth/personhood/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AllocationWeight } from "../../allocation/v1/allocation";
import { Bundle } from "../../shielded/v1/shielded";
import { Params } from "./params";
import { Membership, MoveProof } from "./registration";

export const protobufPackage = "earth.personhood.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /** NOTE: All parameters must be supplied. */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/**
 * MsgRegister registers a passport. Private: unsigned, its fee paid by fee.
 *
 * proof is a passport circuit's UltraHonk proof and public_signals its public
 * inputs as decimal strings (positions are params). The chain verifies it,
 * verifies dsc_der against the CSCA trust store and binds it to the proof's
 * dsc_key, pins current_date to block time, dedups on the passport nullifier,
 * and requires the proof's `address` input to equal
 * zk/privacy.RegistrationBinding =
 *   H(TAG_REG, Bytes(chain_id), idc, pc_anml, Bytes(ciphertext_anml), pc_erth,
 *     Bytes(ciphertext_erth), affiliate)
 * with affiliate = 0 when the registration names no referrer, and
 *   H(TAG_AFFILIATE, Bytes(affiliate_handle))
 * when it does (TAG_AFFILIATE = the field element of the bytes
 * "earth.affiliate"), so whoever relays it cannot swap the handle.
 *
 * A new registration (or one re-entering after its last lapsed) appends the
 * leaf, mints 1 ANML to pc_anml and the registrant's half of the reward to
 * pc_erth, and, when it names affiliate_handle (a live handle: MsgBindHandle),
 * mints the referrer's half itself, to the address the handle resolves to at
 * execution: pc = PC(handle owner_pk, rho, rcm) with
 *   rho = H(TAG_REFERRAL, nullifier, leaf_index, 0)
 *   rcm = H(TAG_REFERRAL, nullifier, leaf_index, 1)
 * (zk/privacy.ReferralOpening; TAG_REFERRAL = "earth.referral", nullifier the
 * passport nullifier, leaf_index the new leaf's). The note has no ciphertext:
 * its shielded_mint event carries owner_pk, rho and rcm, and the handle
 * owner's wallet finds it by owner_pk. The registrant cannot redirect it. A
 * live registration is a switch: the old leaf is zeroed and the new one
 * appended, and nothing is paid (affiliate is then not checked). A switch to
 * the idc the live registration already holds is refused (a replay).
 *
 * sighash fields: idc, pc_anml, Bytes(ciphertext_anml), pc_erth,
 * Bytes(ciphertext_erth), affiliate (as in the binding),
 * Bytes(signature_algorithm), then every public signal in order. The passport
 * proof binds the identity, pcs and ciphertexts through its address input;
 * the sighash binds the rest to the fee bundle.
 */
export interface MsgRegister {
  fee:
    | Bundle
    | undefined;
  /** proof is the Barretenberg UltraHonk proof bytes (bb v5.0.0). */
  proof: Uint8Array;
  /** public_signals are the circuit public inputs as decimal strings. */
  publicSignals: string[];
  /** signature_algorithm selects the verifying key (e.g. "lean_poa_rsa2048_sha256"). */
  signatureAlgorithm: string;
  /** dsc_der is the DER-encoded Document Signer certificate. */
  dscDer: Uint8Array;
  /** idc is the identity commitment H(TAG_ID, id_secret), 32 bytes. */
  idc: Uint8Array;
  /** pc_anml receives the registration's ANML note. */
  pcAnml: Uint8Array;
  /**
   * ciphertext_anml / ciphertext_erth: each note's amount-blind v2
   * ciphertext (zk/privacy.EncryptBlindNote), exactly 177 bytes, required.
   */
  ciphertextAnml: Uint8Array;
  /** pc_erth receives the registrant's half of the registration reward. */
  pcErth: Uint8Array;
  ciphertextErth: Uint8Array;
  /** affiliate_handle names the referrer (a live handle), empty for none. */
  affiliateHandle: string;
}

/** MsgRegisterResponse returns what the registration did. */
export interface MsgRegisterResponse {
  /** reward is the ERTH minted to pc_erth; zero on a switch. */
  reward: string;
  /** switched is true when this moved a live registration to a new identity. */
  switched: boolean;
  /** leaf_index is the new identity leaf's position. */
  leafIndex: number;
}

/**
 * MsgClaimAnml mints 1 ANML to pc, once per person per UTC day.
 *
 * membership is proven with scope zk/privacy.ClaimScope(day), excluded_dsc and
 * excluded_country 0
 * and max_activation the start of the previous UTC day. day must be today.
 *
 * sighash fields: day, pc, Bytes(ciphertext).
 */
export interface MsgClaimAnml {
  fee: Bundle | undefined;
  membership: Membership | undefined;
  day: number;
  pc: Uint8Array;
  /** ciphertext is the ANML note's amount-blind v2 ciphertext, 177 bytes. */
  ciphertext: Uint8Array;
}

/** MsgClaimAnmlResponse returns the ANML note's position. */
export interface MsgClaimAnmlResponse {
  position: number;
}

/**
 * MsgSetCaretaker casts, replaces or clears (empty percentages) the prover's
 * caretaker split. The split is public; who cast it is not.
 *
 * membership is proven with scope zk/privacy.CaretakerScope(), excluded_dsc and
 * excluded_country 0, max_activation NoBound (2^63 - 1: any) and
 * max_predecessor this msg's max_predecessor, which must be strictly below
 * now - caretaker_vote_seconds (or a held, longer one after governance
 * lowered it) - 86400 (one day, the largest identity root window). A fresh
 * registrant (predecessor_at 0) casts at once; an identity that replaced
 * another waits until every split its predecessor could have cast has
 * lapsed (a switch that keeps its split moves it: MsgMoveCaretaker). The
 * bound applies only to a prover holding no split: refreshing or changing
 * one it holds (cast, or moved to it) takes any max_predecessor. A prover
 * that moved its split away may never cast again. The wallet names the
 * bound (rounded down, say to the hour, so it
 * says nothing about when the tx was made) because the chain's own changes
 * every block and a proof must be made before its block is known. The split
 * counts until now + caretaker_vote_seconds; the wallet refreshes it before
 * then.
 *
 * sighash fields: for each entry, option_id then percent.
 */
export interface MsgSetCaretaker {
  fee: Bundle | undefined;
  membership: Membership | undefined;
  percentages: AllocationWeight[];
  /** max_predecessor is the membership proof's max_predecessor (unix seconds). */
  maxPredecessor: number;
}

/**
 * MsgSetCaretakerResponse reports when the split lapses (unix seconds), 0 when
 * it was cleared.
 */
export interface MsgSetCaretakerResponse {
  expiresAt: number;
}

/**
 * MsgMoveCaretaker hands the live caretaker split of an identity,
 * percentages and expiry unchanged, to the identity that succeeded it under
 * the same passport (a switch, or a re-entry), with no wait: one split per
 * passport across the switch.
 *
 * move is a move proof (MoveProof) with scope zk/privacy.CaretakerScope():
 * old_nullifier holds a live split, new_nullifier holds none and never moved
 * one away. old_nullifier may never cast a split again. The proof binds this
 * msg's sighash.
 *
 * sighash fields: none beyond the fee bundle's.
 */
export interface MsgMoveCaretaker {
  fee: Bundle | undefined;
  move: MoveProof | undefined;
}

/** MsgMoveCaretakerResponse reports the moved split's expiry (unix seconds). */
export interface MsgMoveCaretakerResponse {
  expiresAt: number;
}

/**
 * MsgBindHandle claims, renews, changes or releases the prover's handle
 * (types.Handle): a name in the public directory for a shielded address.
 *
 * A handle is lowercase [a-z0-9-], 3 to 32 characters, no leading or
 * trailing dash. One per human: membership is proven with scope zk/privacy.HandleScope()
 * (Scope("handle")), excluded_dsc and excluded_country 0, max_activation
 * NoBound (2^63 - 1) and max_predecessor this msg's max_predecessor.
 *
 *   - handle and address set, the prover holding a handle: renew it (the
 *     same handle: lease now + handle_lease_seconds, address updated) or
 *     change to another (the old one is released at once, the new one
 *     claimed in the same msg). Any max_predecessor while the held handle is
 *     live; in its renewal period, under the claim bound, as a claim.
 *   - handle and address set, the prover holding none: claim a free handle.
 *     max_predecessor must be strictly below now - the longest
 *     handle_lease_seconds ever set - 86400: an identity that replaced
 *     another waits until any handle its predecessor held has lapsed (a
 *     switch that keeps its handle moves it: MsgMoveHandle). A fresh
 *     registrant claims at once. A prover that moved its handle away may
 *     never claim again.
 *   - both empty: release the prover's handle at once.
 *
 * A handle held by another nullifier (live, or in its renewal period) is
 * refused.
 *
 * address is the shielded address (zk/privacy: bech32m "erthz1...", owner_pk
 * and ek_pub), canonical lowercase. No consent is needed: naming someone
 * else's shielded address only sends the binder's referrals to them.
 *
 * sighash fields: Bytes(handle), owner_pk, Bytes(ek_pub) (Bytes of nothing,
 * 0 and Bytes of nothing for a release).
 */
export interface MsgBindHandle {
  fee: Bundle | undefined;
  membership: Membership | undefined;
  handle: string;
  /** address is the shielded address the handle resolves to. */
  address: string;
  /** max_predecessor is the membership proof's max_predecessor (unix seconds). */
  maxPredecessor: number;
}

/**
 * MsgBindHandleResponse reports when the lease lapses (unix seconds), 0 when
 * the handle was released.
 */
export interface MsgBindHandleResponse {
  expiresAt: number;
}

/**
 * MsgMoveHandle hands a live handle, lease unchanged, from an identity to
 * the identity that succeeded it under the same passport (a switch, or a
 * re-entry): how a passport keeps its one handle across a switch. A handle in
 * its renewal period must be renewed first.
 *
 * move is a move proof (MoveProof) with scope zk/privacy.HandleScope():
 * old_nullifier holds `handle`, new_nullifier holds no handle and never moved
 * one away. old_nullifier may never claim a handle again. The proof binds
 * this msg's sighash, and so the handle.
 *
 * sighash fields: Bytes(handle).
 */
export interface MsgMoveHandle {
  fee: Bundle | undefined;
  move: MoveProof | undefined;
  handle: string;
}

/** MsgMoveHandleResponse is empty. */
export interface MsgMoveHandleResponse {
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateParams();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.authority = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.params = Params.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateParamsResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgRegister(): MsgRegister {
  return {
    fee: undefined,
    proof: new Uint8Array(0),
    publicSignals: [],
    signatureAlgorithm: "",
    dscDer: new Uint8Array(0),
    idc: new Uint8Array(0),
    pcAnml: new Uint8Array(0),
    ciphertextAnml: new Uint8Array(0),
    pcErth: new Uint8Array(0),
    ciphertextErth: new Uint8Array(0),
    affiliateHandle: "",
  };
}

export const MsgRegister: MessageFns<MsgRegister> = {
  encode(message: MsgRegister, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fee !== undefined) {
      Bundle.encode(message.fee, writer.uint32(10).fork()).join();
    }
    if (message.proof.length !== 0) {
      writer.uint32(18).bytes(message.proof);
    }
    for (const v of message.publicSignals) {
      writer.uint32(26).string(v!);
    }
    if (message.signatureAlgorithm !== "") {
      writer.uint32(34).string(message.signatureAlgorithm);
    }
    if (message.dscDer.length !== 0) {
      writer.uint32(42).bytes(message.dscDer);
    }
    if (message.idc.length !== 0) {
      writer.uint32(50).bytes(message.idc);
    }
    if (message.pcAnml.length !== 0) {
      writer.uint32(58).bytes(message.pcAnml);
    }
    if (message.ciphertextAnml.length !== 0) {
      writer.uint32(66).bytes(message.ciphertextAnml);
    }
    if (message.pcErth.length !== 0) {
      writer.uint32(74).bytes(message.pcErth);
    }
    if (message.ciphertextErth.length !== 0) {
      writer.uint32(82).bytes(message.ciphertextErth);
    }
    if (message.affiliateHandle !== "") {
      writer.uint32(122).string(message.affiliateHandle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegister {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgRegister();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fee = Bundle.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.proof = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.publicSignals.push(reader.string());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.signatureAlgorithm = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.dscDer = reader.bytes();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.idc = reader.bytes();
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.pcAnml = reader.bytes();
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.ciphertextAnml = reader.bytes();
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.pcErth = reader.bytes();
            continue;
          }
          case 10: {
            if (tag !== 82) {
              break;
            }

            message.ciphertextErth = reader.bytes();
            continue;
          }
          case 15: {
            if (tag !== 122) {
              break;
            }

            message.affiliateHandle = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgRegister {
    return {
      fee: isSet(object.fee) ? Bundle.fromJSON(object.fee) : undefined,
      proof: isSet(object.proof) ? bytesFromBase64(object.proof) : new Uint8Array(0),
      publicSignals: globalThis.Array.isArray(object?.publicSignals)
        ? object.publicSignals.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.public_signals)
        ? object.public_signals.map((e: any) => globalThis.String(e))
        : [],
      signatureAlgorithm: isSet(object.signatureAlgorithm)
        ? globalThis.String(object.signatureAlgorithm)
        : isSet(object.signature_algorithm)
        ? globalThis.String(object.signature_algorithm)
        : "",
      dscDer: isSet(object.dscDer)
        ? bytesFromBase64(object.dscDer)
        : isSet(object.dsc_der)
        ? bytesFromBase64(object.dsc_der)
        : new Uint8Array(0),
      idc: isSet(object.idc) ? bytesFromBase64(object.idc) : new Uint8Array(0),
      pcAnml: isSet(object.pcAnml)
        ? bytesFromBase64(object.pcAnml)
        : isSet(object.pc_anml)
        ? bytesFromBase64(object.pc_anml)
        : new Uint8Array(0),
      ciphertextAnml: isSet(object.ciphertextAnml)
        ? bytesFromBase64(object.ciphertextAnml)
        : isSet(object.ciphertext_anml)
        ? bytesFromBase64(object.ciphertext_anml)
        : new Uint8Array(0),
      pcErth: isSet(object.pcErth)
        ? bytesFromBase64(object.pcErth)
        : isSet(object.pc_erth)
        ? bytesFromBase64(object.pc_erth)
        : new Uint8Array(0),
      ciphertextErth: isSet(object.ciphertextErth)
        ? bytesFromBase64(object.ciphertextErth)
        : isSet(object.ciphertext_erth)
        ? bytesFromBase64(object.ciphertext_erth)
        : new Uint8Array(0),
      affiliateHandle: isSet(object.affiliateHandle)
        ? globalThis.String(object.affiliateHandle)
        : isSet(object.affiliate_handle)
        ? globalThis.String(object.affiliate_handle)
        : "",
    };
  },

  toJSON(message: MsgRegister): unknown {
    const obj: any = {};
    if (message.fee !== undefined) {
      obj.fee = Bundle.toJSON(message.fee);
    }
    if (message.proof.length !== 0) {
      obj.proof = base64FromBytes(message.proof);
    }
    if (message.publicSignals?.length) {
      obj.publicSignals = message.publicSignals;
    }
    if (message.signatureAlgorithm !== "") {
      obj.signatureAlgorithm = message.signatureAlgorithm;
    }
    if (message.dscDer.length !== 0) {
      obj.dscDer = base64FromBytes(message.dscDer);
    }
    if (message.idc.length !== 0) {
      obj.idc = base64FromBytes(message.idc);
    }
    if (message.pcAnml.length !== 0) {
      obj.pcAnml = base64FromBytes(message.pcAnml);
    }
    if (message.ciphertextAnml.length !== 0) {
      obj.ciphertextAnml = base64FromBytes(message.ciphertextAnml);
    }
    if (message.pcErth.length !== 0) {
      obj.pcErth = base64FromBytes(message.pcErth);
    }
    if (message.ciphertextErth.length !== 0) {
      obj.ciphertextErth = base64FromBytes(message.ciphertextErth);
    }
    if (message.affiliateHandle !== "") {
      obj.affiliateHandle = message.affiliateHandle;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegister>, I>>(base?: I): MsgRegister {
    return MsgRegister.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegister>, I>>(object: I): MsgRegister {
    const message = createBaseMsgRegister();
    message.fee = (object.fee !== undefined && object.fee !== null) ? Bundle.fromPartial(object.fee) : undefined;
    message.proof = object.proof ?? new Uint8Array(0);
    message.publicSignals = object.publicSignals?.map((e) => e) || [];
    message.signatureAlgorithm = object.signatureAlgorithm ?? "";
    message.dscDer = object.dscDer ?? new Uint8Array(0);
    message.idc = object.idc ?? new Uint8Array(0);
    message.pcAnml = object.pcAnml ?? new Uint8Array(0);
    message.ciphertextAnml = object.ciphertextAnml ?? new Uint8Array(0);
    message.pcErth = object.pcErth ?? new Uint8Array(0);
    message.ciphertextErth = object.ciphertextErth ?? new Uint8Array(0);
    message.affiliateHandle = object.affiliateHandle ?? "";
    return message;
  },
};

function createBaseMsgRegisterResponse(): MsgRegisterResponse {
  return { reward: "", switched: false, leafIndex: 0 };
}

export const MsgRegisterResponse: MessageFns<MsgRegisterResponse> = {
  encode(message: MsgRegisterResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reward !== "") {
      writer.uint32(10).string(message.reward);
    }
    if (message.switched !== false) {
      writer.uint32(16).bool(message.switched);
    }
    if (message.leafIndex !== 0) {
      writer.uint32(24).uint64(message.leafIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgRegisterResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.reward = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.switched = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.leafIndex = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgRegisterResponse {
    return {
      reward: isSet(object.reward) ? globalThis.String(object.reward) : "",
      switched: isSet(object.switched) ? globalThis.Boolean(object.switched) : false,
      leafIndex: isSet(object.leafIndex)
        ? globalThis.Number(object.leafIndex)
        : isSet(object.leaf_index)
        ? globalThis.Number(object.leaf_index)
        : 0,
    };
  },

  toJSON(message: MsgRegisterResponse): unknown {
    const obj: any = {};
    if (message.reward !== "") {
      obj.reward = message.reward;
    }
    if (message.switched !== false) {
      obj.switched = message.switched;
    }
    if (message.leafIndex !== 0) {
      obj.leafIndex = Math.round(message.leafIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterResponse>, I>>(base?: I): MsgRegisterResponse {
    return MsgRegisterResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterResponse>, I>>(object: I): MsgRegisterResponse {
    const message = createBaseMsgRegisterResponse();
    message.reward = object.reward ?? "";
    message.switched = object.switched ?? false;
    message.leafIndex = object.leafIndex ?? 0;
    return message;
  },
};

function createBaseMsgClaimAnml(): MsgClaimAnml {
  return { fee: undefined, membership: undefined, day: 0, pc: new Uint8Array(0), ciphertext: new Uint8Array(0) };
}

export const MsgClaimAnml: MessageFns<MsgClaimAnml> = {
  encode(message: MsgClaimAnml, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fee !== undefined) {
      Bundle.encode(message.fee, writer.uint32(10).fork()).join();
    }
    if (message.membership !== undefined) {
      Membership.encode(message.membership, writer.uint32(18).fork()).join();
    }
    if (message.day !== 0) {
      writer.uint32(24).uint64(message.day);
    }
    if (message.pc.length !== 0) {
      writer.uint32(34).bytes(message.pc);
    }
    if (message.ciphertext.length !== 0) {
      writer.uint32(42).bytes(message.ciphertext);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgClaimAnml {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgClaimAnml();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fee = Bundle.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.membership = Membership.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.day = longToNumber(reader.uint64());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.pc = reader.bytes();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.ciphertext = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgClaimAnml {
    return {
      fee: isSet(object.fee) ? Bundle.fromJSON(object.fee) : undefined,
      membership: isSet(object.membership) ? Membership.fromJSON(object.membership) : undefined,
      day: isSet(object.day) ? globalThis.Number(object.day) : 0,
      pc: isSet(object.pc) ? bytesFromBase64(object.pc) : new Uint8Array(0),
      ciphertext: isSet(object.ciphertext) ? bytesFromBase64(object.ciphertext) : new Uint8Array(0),
    };
  },

  toJSON(message: MsgClaimAnml): unknown {
    const obj: any = {};
    if (message.fee !== undefined) {
      obj.fee = Bundle.toJSON(message.fee);
    }
    if (message.membership !== undefined) {
      obj.membership = Membership.toJSON(message.membership);
    }
    if (message.day !== 0) {
      obj.day = Math.round(message.day);
    }
    if (message.pc.length !== 0) {
      obj.pc = base64FromBytes(message.pc);
    }
    if (message.ciphertext.length !== 0) {
      obj.ciphertext = base64FromBytes(message.ciphertext);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgClaimAnml>, I>>(base?: I): MsgClaimAnml {
    return MsgClaimAnml.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgClaimAnml>, I>>(object: I): MsgClaimAnml {
    const message = createBaseMsgClaimAnml();
    message.fee = (object.fee !== undefined && object.fee !== null) ? Bundle.fromPartial(object.fee) : undefined;
    message.membership = (object.membership !== undefined && object.membership !== null)
      ? Membership.fromPartial(object.membership)
      : undefined;
    message.day = object.day ?? 0;
    message.pc = object.pc ?? new Uint8Array(0);
    message.ciphertext = object.ciphertext ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgClaimAnmlResponse(): MsgClaimAnmlResponse {
  return { position: 0 };
}

export const MsgClaimAnmlResponse: MessageFns<MsgClaimAnmlResponse> = {
  encode(message: MsgClaimAnmlResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.position !== 0) {
      writer.uint32(8).uint64(message.position);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgClaimAnmlResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgClaimAnmlResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.position = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgClaimAnmlResponse {
    return { position: isSet(object.position) ? globalThis.Number(object.position) : 0 };
  },

  toJSON(message: MsgClaimAnmlResponse): unknown {
    const obj: any = {};
    if (message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgClaimAnmlResponse>, I>>(base?: I): MsgClaimAnmlResponse {
    return MsgClaimAnmlResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgClaimAnmlResponse>, I>>(object: I): MsgClaimAnmlResponse {
    const message = createBaseMsgClaimAnmlResponse();
    message.position = object.position ?? 0;
    return message;
  },
};

function createBaseMsgSetCaretaker(): MsgSetCaretaker {
  return { fee: undefined, membership: undefined, percentages: [], maxPredecessor: 0 };
}

export const MsgSetCaretaker: MessageFns<MsgSetCaretaker> = {
  encode(message: MsgSetCaretaker, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fee !== undefined) {
      Bundle.encode(message.fee, writer.uint32(10).fork()).join();
    }
    if (message.membership !== undefined) {
      Membership.encode(message.membership, writer.uint32(18).fork()).join();
    }
    for (const v of message.percentages) {
      AllocationWeight.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.maxPredecessor !== 0) {
      writer.uint32(40).uint64(message.maxPredecessor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetCaretaker {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgSetCaretaker();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fee = Bundle.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.membership = Membership.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.percentages.push(AllocationWeight.decode(reader, reader.uint32()));
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.maxPredecessor = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgSetCaretaker {
    return {
      fee: isSet(object.fee) ? Bundle.fromJSON(object.fee) : undefined,
      membership: isSet(object.membership) ? Membership.fromJSON(object.membership) : undefined,
      percentages: globalThis.Array.isArray(object?.percentages)
        ? object.percentages.map((e: any) => AllocationWeight.fromJSON(e))
        : [],
      maxPredecessor: isSet(object.maxPredecessor)
        ? globalThis.Number(object.maxPredecessor)
        : isSet(object.max_predecessor)
        ? globalThis.Number(object.max_predecessor)
        : 0,
    };
  },

  toJSON(message: MsgSetCaretaker): unknown {
    const obj: any = {};
    if (message.fee !== undefined) {
      obj.fee = Bundle.toJSON(message.fee);
    }
    if (message.membership !== undefined) {
      obj.membership = Membership.toJSON(message.membership);
    }
    if (message.percentages?.length) {
      obj.percentages = message.percentages.map((e) => AllocationWeight.toJSON(e));
    }
    if (message.maxPredecessor !== 0) {
      obj.maxPredecessor = Math.round(message.maxPredecessor);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetCaretaker>, I>>(base?: I): MsgSetCaretaker {
    return MsgSetCaretaker.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetCaretaker>, I>>(object: I): MsgSetCaretaker {
    const message = createBaseMsgSetCaretaker();
    message.fee = (object.fee !== undefined && object.fee !== null) ? Bundle.fromPartial(object.fee) : undefined;
    message.membership = (object.membership !== undefined && object.membership !== null)
      ? Membership.fromPartial(object.membership)
      : undefined;
    message.percentages = object.percentages?.map((e) => AllocationWeight.fromPartial(e)) || [];
    message.maxPredecessor = object.maxPredecessor ?? 0;
    return message;
  },
};

function createBaseMsgSetCaretakerResponse(): MsgSetCaretakerResponse {
  return { expiresAt: 0 };
}

export const MsgSetCaretakerResponse: MessageFns<MsgSetCaretakerResponse> = {
  encode(message: MsgSetCaretakerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.expiresAt !== 0) {
      writer.uint32(8).int64(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetCaretakerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgSetCaretakerResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.expiresAt = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgSetCaretakerResponse {
    return {
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
    };
  },

  toJSON(message: MsgSetCaretakerResponse): unknown {
    const obj: any = {};
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetCaretakerResponse>, I>>(base?: I): MsgSetCaretakerResponse {
    return MsgSetCaretakerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetCaretakerResponse>, I>>(object: I): MsgSetCaretakerResponse {
    const message = createBaseMsgSetCaretakerResponse();
    message.expiresAt = object.expiresAt ?? 0;
    return message;
  },
};

function createBaseMsgMoveCaretaker(): MsgMoveCaretaker {
  return { fee: undefined, move: undefined };
}

export const MsgMoveCaretaker: MessageFns<MsgMoveCaretaker> = {
  encode(message: MsgMoveCaretaker, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fee !== undefined) {
      Bundle.encode(message.fee, writer.uint32(10).fork()).join();
    }
    if (message.move !== undefined) {
      MoveProof.encode(message.move, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMoveCaretaker {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgMoveCaretaker();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fee = Bundle.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.move = MoveProof.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgMoveCaretaker {
    return {
      fee: isSet(object.fee) ? Bundle.fromJSON(object.fee) : undefined,
      move: isSet(object.move) ? MoveProof.fromJSON(object.move) : undefined,
    };
  },

  toJSON(message: MsgMoveCaretaker): unknown {
    const obj: any = {};
    if (message.fee !== undefined) {
      obj.fee = Bundle.toJSON(message.fee);
    }
    if (message.move !== undefined) {
      obj.move = MoveProof.toJSON(message.move);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMoveCaretaker>, I>>(base?: I): MsgMoveCaretaker {
    return MsgMoveCaretaker.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMoveCaretaker>, I>>(object: I): MsgMoveCaretaker {
    const message = createBaseMsgMoveCaretaker();
    message.fee = (object.fee !== undefined && object.fee !== null) ? Bundle.fromPartial(object.fee) : undefined;
    message.move = (object.move !== undefined && object.move !== null) ? MoveProof.fromPartial(object.move) : undefined;
    return message;
  },
};

function createBaseMsgMoveCaretakerResponse(): MsgMoveCaretakerResponse {
  return { expiresAt: 0 };
}

export const MsgMoveCaretakerResponse: MessageFns<MsgMoveCaretakerResponse> = {
  encode(message: MsgMoveCaretakerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.expiresAt !== 0) {
      writer.uint32(8).int64(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMoveCaretakerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgMoveCaretakerResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.expiresAt = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgMoveCaretakerResponse {
    return {
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
    };
  },

  toJSON(message: MsgMoveCaretakerResponse): unknown {
    const obj: any = {};
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMoveCaretakerResponse>, I>>(base?: I): MsgMoveCaretakerResponse {
    return MsgMoveCaretakerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMoveCaretakerResponse>, I>>(object: I): MsgMoveCaretakerResponse {
    const message = createBaseMsgMoveCaretakerResponse();
    message.expiresAt = object.expiresAt ?? 0;
    return message;
  },
};

function createBaseMsgBindHandle(): MsgBindHandle {
  return { fee: undefined, membership: undefined, handle: "", address: "", maxPredecessor: 0 };
}

export const MsgBindHandle: MessageFns<MsgBindHandle> = {
  encode(message: MsgBindHandle, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fee !== undefined) {
      Bundle.encode(message.fee, writer.uint32(10).fork()).join();
    }
    if (message.membership !== undefined) {
      Membership.encode(message.membership, writer.uint32(18).fork()).join();
    }
    if (message.handle !== "") {
      writer.uint32(26).string(message.handle);
    }
    if (message.address !== "") {
      writer.uint32(34).string(message.address);
    }
    if (message.maxPredecessor !== 0) {
      writer.uint32(48).uint64(message.maxPredecessor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBindHandle {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgBindHandle();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fee = Bundle.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.membership = Membership.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.handle = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.address = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.maxPredecessor = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgBindHandle {
    return {
      fee: isSet(object.fee) ? Bundle.fromJSON(object.fee) : undefined,
      membership: isSet(object.membership) ? Membership.fromJSON(object.membership) : undefined,
      handle: isSet(object.handle) ? globalThis.String(object.handle) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      maxPredecessor: isSet(object.maxPredecessor)
        ? globalThis.Number(object.maxPredecessor)
        : isSet(object.max_predecessor)
        ? globalThis.Number(object.max_predecessor)
        : 0,
    };
  },

  toJSON(message: MsgBindHandle): unknown {
    const obj: any = {};
    if (message.fee !== undefined) {
      obj.fee = Bundle.toJSON(message.fee);
    }
    if (message.membership !== undefined) {
      obj.membership = Membership.toJSON(message.membership);
    }
    if (message.handle !== "") {
      obj.handle = message.handle;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.maxPredecessor !== 0) {
      obj.maxPredecessor = Math.round(message.maxPredecessor);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBindHandle>, I>>(base?: I): MsgBindHandle {
    return MsgBindHandle.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBindHandle>, I>>(object: I): MsgBindHandle {
    const message = createBaseMsgBindHandle();
    message.fee = (object.fee !== undefined && object.fee !== null) ? Bundle.fromPartial(object.fee) : undefined;
    message.membership = (object.membership !== undefined && object.membership !== null)
      ? Membership.fromPartial(object.membership)
      : undefined;
    message.handle = object.handle ?? "";
    message.address = object.address ?? "";
    message.maxPredecessor = object.maxPredecessor ?? 0;
    return message;
  },
};

function createBaseMsgBindHandleResponse(): MsgBindHandleResponse {
  return { expiresAt: 0 };
}

export const MsgBindHandleResponse: MessageFns<MsgBindHandleResponse> = {
  encode(message: MsgBindHandleResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.expiresAt !== 0) {
      writer.uint32(8).int64(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBindHandleResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgBindHandleResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.expiresAt = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgBindHandleResponse {
    return {
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
    };
  },

  toJSON(message: MsgBindHandleResponse): unknown {
    const obj: any = {};
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBindHandleResponse>, I>>(base?: I): MsgBindHandleResponse {
    return MsgBindHandleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBindHandleResponse>, I>>(object: I): MsgBindHandleResponse {
    const message = createBaseMsgBindHandleResponse();
    message.expiresAt = object.expiresAt ?? 0;
    return message;
  },
};

function createBaseMsgMoveHandle(): MsgMoveHandle {
  return { fee: undefined, move: undefined, handle: "" };
}

export const MsgMoveHandle: MessageFns<MsgMoveHandle> = {
  encode(message: MsgMoveHandle, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fee !== undefined) {
      Bundle.encode(message.fee, writer.uint32(10).fork()).join();
    }
    if (message.move !== undefined) {
      MoveProof.encode(message.move, writer.uint32(18).fork()).join();
    }
    if (message.handle !== "") {
      writer.uint32(26).string(message.handle);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMoveHandle {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgMoveHandle();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fee = Bundle.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.move = MoveProof.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.handle = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgMoveHandle {
    return {
      fee: isSet(object.fee) ? Bundle.fromJSON(object.fee) : undefined,
      move: isSet(object.move) ? MoveProof.fromJSON(object.move) : undefined,
      handle: isSet(object.handle) ? globalThis.String(object.handle) : "",
    };
  },

  toJSON(message: MsgMoveHandle): unknown {
    const obj: any = {};
    if (message.fee !== undefined) {
      obj.fee = Bundle.toJSON(message.fee);
    }
    if (message.move !== undefined) {
      obj.move = MoveProof.toJSON(message.move);
    }
    if (message.handle !== "") {
      obj.handle = message.handle;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMoveHandle>, I>>(base?: I): MsgMoveHandle {
    return MsgMoveHandle.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMoveHandle>, I>>(object: I): MsgMoveHandle {
    const message = createBaseMsgMoveHandle();
    message.fee = (object.fee !== undefined && object.fee !== null) ? Bundle.fromPartial(object.fee) : undefined;
    message.move = (object.move !== undefined && object.move !== null) ? MoveProof.fromPartial(object.move) : undefined;
    message.handle = object.handle ?? "";
    return message;
  },
};

function createBaseMsgMoveHandleResponse(): MsgMoveHandleResponse {
  return {};
}

export const MsgMoveHandleResponse: MessageFns<MsgMoveHandleResponse> = {
  encode(_: MsgMoveHandleResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMoveHandleResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgMoveHandleResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgMoveHandleResponse {
    return {};
  },

  toJSON(_: MsgMoveHandleResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMoveHandleResponse>, I>>(base?: I): MsgMoveHandleResponse {
    return MsgMoveHandleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMoveHandleResponse>, I>>(_: I): MsgMoveHandleResponse {
    const message = createBaseMsgMoveHandleResponse();
    return message;
  },
};

/**
 * Msg defines the Msg service.
 *
 * Register, ClaimAnml, SetCaretaker, MoveCaretaker, BindHandle and MoveHandle are
 * private msgs:
 * unsigned, carried
 * alone in a tx, their fee paid from the shielded pool by the earth.shielded
 * Bundle each embeds as `fee` (see x/shielded PrivateMsg), whose only balance
 * is the uerth fee. Their sighash is zk/orchard.Sighash(type URL, chain id,
 * tx fields (memo, timeout_height, gas_limit), 1, digest(fee), fields...),
 * which every action proof and the binding signature
 * bind, and which a membership proof binds as its signal. The fields are
 * listed on each msg.
 */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** Register registers a passport and writes its holder's identity leaf. */
  Register(request: MsgRegister): Promise<MsgRegisterResponse>;
  /** ClaimAnml mints a registered human's daily ANML to a note. */
  ClaimAnml(request: MsgClaimAnml): Promise<MsgClaimAnmlResponse>;
  /** SetCaretaker casts or refreshes a registered human's caretaker split. */
  SetCaretaker(request: MsgSetCaretaker): Promise<MsgSetCaretakerResponse>;
  /**
   * BindHandle claims, refreshes, changes or releases a registered human's
   * handle: a name in the public directory for a shielded address.
   */
  BindHandle(request: MsgBindHandle): Promise<MsgBindHandleResponse>;
  /**
   * MoveHandle hands an identity's handle to the identity that succeeded it
   * under the same passport (a move proof).
   */
  MoveHandle(request: MsgMoveHandle): Promise<MsgMoveHandleResponse>;
  /**
   * MoveCaretaker hands an identity's live caretaker split (and its expiry)
   * to the identity that succeeded it under the same passport.
   */
  MoveCaretaker(request: MsgMoveCaretaker): Promise<MsgMoveCaretakerResponse>;
}

export const MsgServiceName = "earth.personhood.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.Register = this.Register.bind(this);
    this.ClaimAnml = this.ClaimAnml.bind(this);
    this.SetCaretaker = this.SetCaretaker.bind(this);
    this.BindHandle = this.BindHandle.bind(this);
    this.MoveHandle = this.MoveHandle.bind(this);
    this.MoveCaretaker = this.MoveCaretaker.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  Register(request: MsgRegister): Promise<MsgRegisterResponse> {
    const data = MsgRegister.encode(request).finish();
    const promise = this.rpc.request(this.service, "Register", data);
    return promise.then((data) => MsgRegisterResponse.decode(new BinaryReader(data)));
  }

  ClaimAnml(request: MsgClaimAnml): Promise<MsgClaimAnmlResponse> {
    const data = MsgClaimAnml.encode(request).finish();
    const promise = this.rpc.request(this.service, "ClaimAnml", data);
    return promise.then((data) => MsgClaimAnmlResponse.decode(new BinaryReader(data)));
  }

  SetCaretaker(request: MsgSetCaretaker): Promise<MsgSetCaretakerResponse> {
    const data = MsgSetCaretaker.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetCaretaker", data);
    return promise.then((data) => MsgSetCaretakerResponse.decode(new BinaryReader(data)));
  }

  BindHandle(request: MsgBindHandle): Promise<MsgBindHandleResponse> {
    const data = MsgBindHandle.encode(request).finish();
    const promise = this.rpc.request(this.service, "BindHandle", data);
    return promise.then((data) => MsgBindHandleResponse.decode(new BinaryReader(data)));
  }

  MoveHandle(request: MsgMoveHandle): Promise<MsgMoveHandleResponse> {
    const data = MsgMoveHandle.encode(request).finish();
    const promise = this.rpc.request(this.service, "MoveHandle", data);
    return promise.then((data) => MsgMoveHandleResponse.decode(new BinaryReader(data)));
  }

  MoveCaretaker(request: MsgMoveCaretaker): Promise<MsgMoveCaretakerResponse> {
    const data = MsgMoveCaretaker.encode(request).finish();
    const promise = this.rpc.request(this.service, "MoveCaretaker", data);
    return promise.then((data) => MsgMoveCaretakerResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
