// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: earth/personhood/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AllocationWeight } from "../../allocation/v1/allocation";
import { Transfer } from "../../shielded/v1/shielded";
import { Params } from "./params";
import { Membership } from "./registration";

export const protobufPackage = "earth.personhood.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /** NOTE: All parameters must be supplied. */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/**
 * MsgRegister registers a passport. Private: unsigned, its fee paid by fee.
 *
 * proof is a passport circuit's UltraHonk proof and public_signals its public
 * inputs as decimal strings (positions are params). The chain verifies it,
 * verifies dsc_der against the CSCA trust store and binds it to the proof's
 * dsc_key, pins current_date to block time, dedups on the passport nullifier,
 * and requires the proof's `address` input to equal
 * zk/privacy.RegistrationBinding(idc, pc_anml, pc_erth, affiliate) with
 * affiliate = Bytes(the affiliate's address bytes), 0 when none.
 *
 * A new registration (or one re-entering after its last lapsed) appends the
 * leaf, mints 1 ANML to pc_anml and the registrant's half of the reward to
 * pc_erth, and pays the referrer's half in transparent ERTH to affiliate,
 * which must hold a live referrer binding (MsgBindReferrer). A live
 * registration is a switch: the old leaf is zeroed and the new one appended,
 * and nothing is paid (affiliate is then not checked).
 *
 * signal fields: idc, pc_anml, Bytes(ciphertext_anml), pc_erth,
 * Bytes(ciphertext_erth), affiliate (as in the binding),
 * Bytes(signature_algorithm), then every public signal in order. The passport proof binds the identity and pcs through its
 * address input; this binds the rest to the fee proof.
 */
export interface MsgRegister {
  fee:
    | Transfer
    | undefined;
  /** proof is the Barretenberg UltraHonk proof bytes (bb v5.0.0). */
  proof: Uint8Array;
  /** public_signals are the circuit public inputs as decimal strings. */
  publicSignals: string[];
  /** signature_algorithm selects the verifying key (e.g. "lean_poa"). */
  signatureAlgorithm: string;
  /** dsc_der is the DER-encoded Document Signer certificate. */
  dscDer: Uint8Array;
  /** idc is the identity commitment H(TAG_ID, id_secret), 32 bytes. */
  idc: Uint8Array;
  /** pc_anml receives the registration's ANML note. */
  pcAnml: Uint8Array;
  ciphertextAnml: Uint8Array;
  /** pc_erth receives the registrant's half of the registration reward. */
  pcErth: Uint8Array;
  ciphertextErth: Uint8Array;
  /**
   * affiliate is the referrer's address (bech32), empty for none. It must
   * hold a live referrer binding, and receives the referrer's half of the
   * reward in transparent ERTH.
   */
  affiliate: string;
}

/** MsgRegisterResponse returns what the registration did. */
export interface MsgRegisterResponse {
  /** reward is the ERTH minted to pc_erth; zero on a switch. */
  reward: string;
  /** switched is true when this moved a live registration to a new identity. */
  switched: boolean;
  /** leaf_index is the new identity leaf's position. */
  leafIndex: number;
}

/**
 * MsgClaimAnml mints 1 ANML to pc, once per person per UTC day.
 *
 * membership is proven with scope zk/privacy.ClaimScope(day), excluded_dsc and
 * excluded_country 0
 * and max_activation the start of the previous UTC day. day must be today.
 *
 * signal fields: day, pc, Bytes(ciphertext).
 */
export interface MsgClaimAnml {
  fee: Transfer | undefined;
  membership: Membership | undefined;
  day: number;
  pc: Uint8Array;
  ciphertext: Uint8Array;
}

/** MsgClaimAnmlResponse returns the ANML note's position. */
export interface MsgClaimAnmlResponse {
  position: number;
}

/**
 * MsgSetCaretaker casts, replaces or clears (empty percentages) the prover's
 * caretaker split. The split is public; who cast it is not.
 *
 * membership is proven with scope zk/privacy.CaretakerScope(), excluded_dsc and
 * excluded_country 0
 * and max_activation this msg's max_activation, which must be at most now -
 * caretaker_vote_seconds - identity_root_window_seconds. The wallet names the
 * bound (rounded down, say to the hour, so it says nothing about when the tx
 * was made) because the chain's own changes every block and a proof must be
 * made before its block is known. The split counts until now +
 * caretaker_vote_seconds; the wallet refreshes it before then.
 *
 * signal fields: for each entry, option_id then percent.
 */
export interface MsgSetCaretaker {
  fee: Transfer | undefined;
  membership: Membership | undefined;
  percentages: AllocationWeight[];
  /** max_activation is the membership proof's max_activation (unix seconds). */
  maxActivation: number;
}

/**
 * MsgSetCaretakerResponse reports when the split lapses (unix seconds), 0 when
 * it was cleared.
 */
export interface MsgSetCaretakerResponse {
  expiresAt: number;
}

/**
 * MsgBindReferrer binds address as the prover's referral address, or clears
 * the binding (empty address). Referrals are public: a registration naming
 * address pays the referrer's half of its reward there, in transparent ERTH.
 * Who bound it is not public; that a live registration did, is.
 *
 * membership is proven with scope zk/privacy.ReferrerScope(), excluded_dsc
 * and excluded_country 0 and max_activation this msg's max_activation, which
 * must be at most now - caretaker_vote_seconds - identity_root_window_seconds
 * (the caretaker rule: a switched-to identity cannot hold a binding beside
 * its predecessor's). The binding lasts caretaker_vote_seconds; the wallet
 * refreshes it. Rebinding under the same nullifier moves it to the new
 * address. An address bound under another live nullifier is refused.
 *
 * signal fields: Bytes(address bytes).
 */
export interface MsgBindReferrer {
  fee: Transfer | undefined;
  membership: Membership | undefined;
  address: string;
  /** max_activation is the membership proof's max_activation (unix seconds). */
  maxActivation: number;
}

/**
 * MsgBindReferrerResponse reports when the binding lapses (unix seconds), 0
 * when it was cleared.
 */
export interface MsgBindReferrerResponse {
  expiresAt: number;
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateParams();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.authority = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.params = Params.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateParamsResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgRegister(): MsgRegister {
  return {
    fee: undefined,
    proof: new Uint8Array(0),
    publicSignals: [],
    signatureAlgorithm: "",
    dscDer: new Uint8Array(0),
    idc: new Uint8Array(0),
    pcAnml: new Uint8Array(0),
    ciphertextAnml: new Uint8Array(0),
    pcErth: new Uint8Array(0),
    ciphertextErth: new Uint8Array(0),
    affiliate: "",
  };
}

export const MsgRegister: MessageFns<MsgRegister> = {
  encode(message: MsgRegister, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fee !== undefined) {
      Transfer.encode(message.fee, writer.uint32(10).fork()).join();
    }
    if (message.proof.length !== 0) {
      writer.uint32(18).bytes(message.proof);
    }
    for (const v of message.publicSignals) {
      writer.uint32(26).string(v!);
    }
    if (message.signatureAlgorithm !== "") {
      writer.uint32(34).string(message.signatureAlgorithm);
    }
    if (message.dscDer.length !== 0) {
      writer.uint32(42).bytes(message.dscDer);
    }
    if (message.idc.length !== 0) {
      writer.uint32(50).bytes(message.idc);
    }
    if (message.pcAnml.length !== 0) {
      writer.uint32(58).bytes(message.pcAnml);
    }
    if (message.ciphertextAnml.length !== 0) {
      writer.uint32(66).bytes(message.ciphertextAnml);
    }
    if (message.pcErth.length !== 0) {
      writer.uint32(74).bytes(message.pcErth);
    }
    if (message.ciphertextErth.length !== 0) {
      writer.uint32(82).bytes(message.ciphertextErth);
    }
    if (message.affiliate !== "") {
      writer.uint32(106).string(message.affiliate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegister {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgRegister();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fee = Transfer.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.proof = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.publicSignals.push(reader.string());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.signatureAlgorithm = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.dscDer = reader.bytes();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.idc = reader.bytes();
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.pcAnml = reader.bytes();
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.ciphertextAnml = reader.bytes();
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.pcErth = reader.bytes();
            continue;
          }
          case 10: {
            if (tag !== 82) {
              break;
            }

            message.ciphertextErth = reader.bytes();
            continue;
          }
          case 13: {
            if (tag !== 106) {
              break;
            }

            message.affiliate = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgRegister {
    return {
      fee: isSet(object.fee) ? Transfer.fromJSON(object.fee) : undefined,
      proof: isSet(object.proof) ? bytesFromBase64(object.proof) : new Uint8Array(0),
      publicSignals: globalThis.Array.isArray(object?.publicSignals)
        ? object.publicSignals.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.public_signals)
        ? object.public_signals.map((e: any) => globalThis.String(e))
        : [],
      signatureAlgorithm: isSet(object.signatureAlgorithm)
        ? globalThis.String(object.signatureAlgorithm)
        : isSet(object.signature_algorithm)
        ? globalThis.String(object.signature_algorithm)
        : "",
      dscDer: isSet(object.dscDer)
        ? bytesFromBase64(object.dscDer)
        : isSet(object.dsc_der)
        ? bytesFromBase64(object.dsc_der)
        : new Uint8Array(0),
      idc: isSet(object.idc) ? bytesFromBase64(object.idc) : new Uint8Array(0),
      pcAnml: isSet(object.pcAnml)
        ? bytesFromBase64(object.pcAnml)
        : isSet(object.pc_anml)
        ? bytesFromBase64(object.pc_anml)
        : new Uint8Array(0),
      ciphertextAnml: isSet(object.ciphertextAnml)
        ? bytesFromBase64(object.ciphertextAnml)
        : isSet(object.ciphertext_anml)
        ? bytesFromBase64(object.ciphertext_anml)
        : new Uint8Array(0),
      pcErth: isSet(object.pcErth)
        ? bytesFromBase64(object.pcErth)
        : isSet(object.pc_erth)
        ? bytesFromBase64(object.pc_erth)
        : new Uint8Array(0),
      ciphertextErth: isSet(object.ciphertextErth)
        ? bytesFromBase64(object.ciphertextErth)
        : isSet(object.ciphertext_erth)
        ? bytesFromBase64(object.ciphertext_erth)
        : new Uint8Array(0),
      affiliate: isSet(object.affiliate) ? globalThis.String(object.affiliate) : "",
    };
  },

  toJSON(message: MsgRegister): unknown {
    const obj: any = {};
    if (message.fee !== undefined) {
      obj.fee = Transfer.toJSON(message.fee);
    }
    if (message.proof.length !== 0) {
      obj.proof = base64FromBytes(message.proof);
    }
    if (message.publicSignals?.length) {
      obj.publicSignals = message.publicSignals;
    }
    if (message.signatureAlgorithm !== "") {
      obj.signatureAlgorithm = message.signatureAlgorithm;
    }
    if (message.dscDer.length !== 0) {
      obj.dscDer = base64FromBytes(message.dscDer);
    }
    if (message.idc.length !== 0) {
      obj.idc = base64FromBytes(message.idc);
    }
    if (message.pcAnml.length !== 0) {
      obj.pcAnml = base64FromBytes(message.pcAnml);
    }
    if (message.ciphertextAnml.length !== 0) {
      obj.ciphertextAnml = base64FromBytes(message.ciphertextAnml);
    }
    if (message.pcErth.length !== 0) {
      obj.pcErth = base64FromBytes(message.pcErth);
    }
    if (message.ciphertextErth.length !== 0) {
      obj.ciphertextErth = base64FromBytes(message.ciphertextErth);
    }
    if (message.affiliate !== "") {
      obj.affiliate = message.affiliate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegister>, I>>(base?: I): MsgRegister {
    return MsgRegister.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegister>, I>>(object: I): MsgRegister {
    const message = createBaseMsgRegister();
    message.fee = (object.fee !== undefined && object.fee !== null) ? Transfer.fromPartial(object.fee) : undefined;
    message.proof = object.proof ?? new Uint8Array(0);
    message.publicSignals = object.publicSignals?.map((e) => e) || [];
    message.signatureAlgorithm = object.signatureAlgorithm ?? "";
    message.dscDer = object.dscDer ?? new Uint8Array(0);
    message.idc = object.idc ?? new Uint8Array(0);
    message.pcAnml = object.pcAnml ?? new Uint8Array(0);
    message.ciphertextAnml = object.ciphertextAnml ?? new Uint8Array(0);
    message.pcErth = object.pcErth ?? new Uint8Array(0);
    message.ciphertextErth = object.ciphertextErth ?? new Uint8Array(0);
    message.affiliate = object.affiliate ?? "";
    return message;
  },
};

function createBaseMsgRegisterResponse(): MsgRegisterResponse {
  return { reward: "", switched: false, leafIndex: 0 };
}

export const MsgRegisterResponse: MessageFns<MsgRegisterResponse> = {
  encode(message: MsgRegisterResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reward !== "") {
      writer.uint32(10).string(message.reward);
    }
    if (message.switched !== false) {
      writer.uint32(16).bool(message.switched);
    }
    if (message.leafIndex !== 0) {
      writer.uint32(24).uint64(message.leafIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgRegisterResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.reward = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.switched = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.leafIndex = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgRegisterResponse {
    return {
      reward: isSet(object.reward) ? globalThis.String(object.reward) : "",
      switched: isSet(object.switched) ? globalThis.Boolean(object.switched) : false,
      leafIndex: isSet(object.leafIndex)
        ? globalThis.Number(object.leafIndex)
        : isSet(object.leaf_index)
        ? globalThis.Number(object.leaf_index)
        : 0,
    };
  },

  toJSON(message: MsgRegisterResponse): unknown {
    const obj: any = {};
    if (message.reward !== "") {
      obj.reward = message.reward;
    }
    if (message.switched !== false) {
      obj.switched = message.switched;
    }
    if (message.leafIndex !== 0) {
      obj.leafIndex = Math.round(message.leafIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterResponse>, I>>(base?: I): MsgRegisterResponse {
    return MsgRegisterResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterResponse>, I>>(object: I): MsgRegisterResponse {
    const message = createBaseMsgRegisterResponse();
    message.reward = object.reward ?? "";
    message.switched = object.switched ?? false;
    message.leafIndex = object.leafIndex ?? 0;
    return message;
  },
};

function createBaseMsgClaimAnml(): MsgClaimAnml {
  return { fee: undefined, membership: undefined, day: 0, pc: new Uint8Array(0), ciphertext: new Uint8Array(0) };
}

export const MsgClaimAnml: MessageFns<MsgClaimAnml> = {
  encode(message: MsgClaimAnml, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fee !== undefined) {
      Transfer.encode(message.fee, writer.uint32(10).fork()).join();
    }
    if (message.membership !== undefined) {
      Membership.encode(message.membership, writer.uint32(18).fork()).join();
    }
    if (message.day !== 0) {
      writer.uint32(24).uint64(message.day);
    }
    if (message.pc.length !== 0) {
      writer.uint32(34).bytes(message.pc);
    }
    if (message.ciphertext.length !== 0) {
      writer.uint32(42).bytes(message.ciphertext);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgClaimAnml {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgClaimAnml();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fee = Transfer.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.membership = Membership.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.day = longToNumber(reader.uint64());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.pc = reader.bytes();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.ciphertext = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgClaimAnml {
    return {
      fee: isSet(object.fee) ? Transfer.fromJSON(object.fee) : undefined,
      membership: isSet(object.membership) ? Membership.fromJSON(object.membership) : undefined,
      day: isSet(object.day) ? globalThis.Number(object.day) : 0,
      pc: isSet(object.pc) ? bytesFromBase64(object.pc) : new Uint8Array(0),
      ciphertext: isSet(object.ciphertext) ? bytesFromBase64(object.ciphertext) : new Uint8Array(0),
    };
  },

  toJSON(message: MsgClaimAnml): unknown {
    const obj: any = {};
    if (message.fee !== undefined) {
      obj.fee = Transfer.toJSON(message.fee);
    }
    if (message.membership !== undefined) {
      obj.membership = Membership.toJSON(message.membership);
    }
    if (message.day !== 0) {
      obj.day = Math.round(message.day);
    }
    if (message.pc.length !== 0) {
      obj.pc = base64FromBytes(message.pc);
    }
    if (message.ciphertext.length !== 0) {
      obj.ciphertext = base64FromBytes(message.ciphertext);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgClaimAnml>, I>>(base?: I): MsgClaimAnml {
    return MsgClaimAnml.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgClaimAnml>, I>>(object: I): MsgClaimAnml {
    const message = createBaseMsgClaimAnml();
    message.fee = (object.fee !== undefined && object.fee !== null) ? Transfer.fromPartial(object.fee) : undefined;
    message.membership = (object.membership !== undefined && object.membership !== null)
      ? Membership.fromPartial(object.membership)
      : undefined;
    message.day = object.day ?? 0;
    message.pc = object.pc ?? new Uint8Array(0);
    message.ciphertext = object.ciphertext ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgClaimAnmlResponse(): MsgClaimAnmlResponse {
  return { position: 0 };
}

export const MsgClaimAnmlResponse: MessageFns<MsgClaimAnmlResponse> = {
  encode(message: MsgClaimAnmlResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.position !== 0) {
      writer.uint32(8).uint64(message.position);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgClaimAnmlResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgClaimAnmlResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.position = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgClaimAnmlResponse {
    return { position: isSet(object.position) ? globalThis.Number(object.position) : 0 };
  },

  toJSON(message: MsgClaimAnmlResponse): unknown {
    const obj: any = {};
    if (message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgClaimAnmlResponse>, I>>(base?: I): MsgClaimAnmlResponse {
    return MsgClaimAnmlResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgClaimAnmlResponse>, I>>(object: I): MsgClaimAnmlResponse {
    const message = createBaseMsgClaimAnmlResponse();
    message.position = object.position ?? 0;
    return message;
  },
};

function createBaseMsgSetCaretaker(): MsgSetCaretaker {
  return { fee: undefined, membership: undefined, percentages: [], maxActivation: 0 };
}

export const MsgSetCaretaker: MessageFns<MsgSetCaretaker> = {
  encode(message: MsgSetCaretaker, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fee !== undefined) {
      Transfer.encode(message.fee, writer.uint32(10).fork()).join();
    }
    if (message.membership !== undefined) {
      Membership.encode(message.membership, writer.uint32(18).fork()).join();
    }
    for (const v of message.percentages) {
      AllocationWeight.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.maxActivation !== 0) {
      writer.uint32(32).uint64(message.maxActivation);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetCaretaker {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgSetCaretaker();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fee = Transfer.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.membership = Membership.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.percentages.push(AllocationWeight.decode(reader, reader.uint32()));
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.maxActivation = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgSetCaretaker {
    return {
      fee: isSet(object.fee) ? Transfer.fromJSON(object.fee) : undefined,
      membership: isSet(object.membership) ? Membership.fromJSON(object.membership) : undefined,
      percentages: globalThis.Array.isArray(object?.percentages)
        ? object.percentages.map((e: any) => AllocationWeight.fromJSON(e))
        : [],
      maxActivation: isSet(object.maxActivation)
        ? globalThis.Number(object.maxActivation)
        : isSet(object.max_activation)
        ? globalThis.Number(object.max_activation)
        : 0,
    };
  },

  toJSON(message: MsgSetCaretaker): unknown {
    const obj: any = {};
    if (message.fee !== undefined) {
      obj.fee = Transfer.toJSON(message.fee);
    }
    if (message.membership !== undefined) {
      obj.membership = Membership.toJSON(message.membership);
    }
    if (message.percentages?.length) {
      obj.percentages = message.percentages.map((e) => AllocationWeight.toJSON(e));
    }
    if (message.maxActivation !== 0) {
      obj.maxActivation = Math.round(message.maxActivation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetCaretaker>, I>>(base?: I): MsgSetCaretaker {
    return MsgSetCaretaker.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetCaretaker>, I>>(object: I): MsgSetCaretaker {
    const message = createBaseMsgSetCaretaker();
    message.fee = (object.fee !== undefined && object.fee !== null) ? Transfer.fromPartial(object.fee) : undefined;
    message.membership = (object.membership !== undefined && object.membership !== null)
      ? Membership.fromPartial(object.membership)
      : undefined;
    message.percentages = object.percentages?.map((e) => AllocationWeight.fromPartial(e)) || [];
    message.maxActivation = object.maxActivation ?? 0;
    return message;
  },
};

function createBaseMsgSetCaretakerResponse(): MsgSetCaretakerResponse {
  return { expiresAt: 0 };
}

export const MsgSetCaretakerResponse: MessageFns<MsgSetCaretakerResponse> = {
  encode(message: MsgSetCaretakerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.expiresAt !== 0) {
      writer.uint32(8).int64(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetCaretakerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgSetCaretakerResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.expiresAt = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgSetCaretakerResponse {
    return {
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
    };
  },

  toJSON(message: MsgSetCaretakerResponse): unknown {
    const obj: any = {};
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetCaretakerResponse>, I>>(base?: I): MsgSetCaretakerResponse {
    return MsgSetCaretakerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetCaretakerResponse>, I>>(object: I): MsgSetCaretakerResponse {
    const message = createBaseMsgSetCaretakerResponse();
    message.expiresAt = object.expiresAt ?? 0;
    return message;
  },
};

function createBaseMsgBindReferrer(): MsgBindReferrer {
  return { fee: undefined, membership: undefined, address: "", maxActivation: 0 };
}

export const MsgBindReferrer: MessageFns<MsgBindReferrer> = {
  encode(message: MsgBindReferrer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fee !== undefined) {
      Transfer.encode(message.fee, writer.uint32(10).fork()).join();
    }
    if (message.membership !== undefined) {
      Membership.encode(message.membership, writer.uint32(18).fork()).join();
    }
    if (message.address !== "") {
      writer.uint32(26).string(message.address);
    }
    if (message.maxActivation !== 0) {
      writer.uint32(32).uint64(message.maxActivation);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBindReferrer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgBindReferrer();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.fee = Transfer.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.membership = Membership.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.address = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.maxActivation = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgBindReferrer {
    return {
      fee: isSet(object.fee) ? Transfer.fromJSON(object.fee) : undefined,
      membership: isSet(object.membership) ? Membership.fromJSON(object.membership) : undefined,
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      maxActivation: isSet(object.maxActivation)
        ? globalThis.Number(object.maxActivation)
        : isSet(object.max_activation)
        ? globalThis.Number(object.max_activation)
        : 0,
    };
  },

  toJSON(message: MsgBindReferrer): unknown {
    const obj: any = {};
    if (message.fee !== undefined) {
      obj.fee = Transfer.toJSON(message.fee);
    }
    if (message.membership !== undefined) {
      obj.membership = Membership.toJSON(message.membership);
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.maxActivation !== 0) {
      obj.maxActivation = Math.round(message.maxActivation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBindReferrer>, I>>(base?: I): MsgBindReferrer {
    return MsgBindReferrer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBindReferrer>, I>>(object: I): MsgBindReferrer {
    const message = createBaseMsgBindReferrer();
    message.fee = (object.fee !== undefined && object.fee !== null) ? Transfer.fromPartial(object.fee) : undefined;
    message.membership = (object.membership !== undefined && object.membership !== null)
      ? Membership.fromPartial(object.membership)
      : undefined;
    message.address = object.address ?? "";
    message.maxActivation = object.maxActivation ?? 0;
    return message;
  },
};

function createBaseMsgBindReferrerResponse(): MsgBindReferrerResponse {
  return { expiresAt: 0 };
}

export const MsgBindReferrerResponse: MessageFns<MsgBindReferrerResponse> = {
  encode(message: MsgBindReferrerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.expiresAt !== 0) {
      writer.uint32(8).int64(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBindReferrerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgBindReferrerResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.expiresAt = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgBindReferrerResponse {
    return {
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
    };
  },

  toJSON(message: MsgBindReferrerResponse): unknown {
    const obj: any = {};
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBindReferrerResponse>, I>>(base?: I): MsgBindReferrerResponse {
    return MsgBindReferrerResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBindReferrerResponse>, I>>(object: I): MsgBindReferrerResponse {
    const message = createBaseMsgBindReferrerResponse();
    message.expiresAt = object.expiresAt ?? 0;
    return message;
  },
};

/**
 * Msg defines the Msg service.
 *
 * Register, ClaimAnml, SetCaretaker and BindReferrer are private msgs:
 * unsigned, carried
 * alone in a tx, their fee paid from the shielded pool by the earth.shielded
 * Transfer each embeds (see x/shielded PrivateMsg). Their signal is
 * zk/privacy.ActionSignal(type URL, chain id, fee ciphertexts, fee
 * nullifiers, fields...), which the fee proof and the msg's own proof both
 * bind. The fields are listed on each msg.
 */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** Register registers a passport and writes its holder's identity leaf. */
  Register(request: MsgRegister): Promise<MsgRegisterResponse>;
  /** ClaimAnml mints a registered human's daily ANML to a note. */
  ClaimAnml(request: MsgClaimAnml): Promise<MsgClaimAnmlResponse>;
  /** SetCaretaker casts or refreshes a registered human's caretaker split. */
  SetCaretaker(request: MsgSetCaretaker): Promise<MsgSetCaretakerResponse>;
  /**
   * BindReferrer names (or clears) the address a registered human is paid
   * referral rewards at.
   */
  BindReferrer(request: MsgBindReferrer): Promise<MsgBindReferrerResponse>;
}

export const MsgServiceName = "earth.personhood.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.Register = this.Register.bind(this);
    this.ClaimAnml = this.ClaimAnml.bind(this);
    this.SetCaretaker = this.SetCaretaker.bind(this);
    this.BindReferrer = this.BindReferrer.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  Register(request: MsgRegister): Promise<MsgRegisterResponse> {
    const data = MsgRegister.encode(request).finish();
    const promise = this.rpc.request(this.service, "Register", data);
    return promise.then((data) => MsgRegisterResponse.decode(new BinaryReader(data)));
  }

  ClaimAnml(request: MsgClaimAnml): Promise<MsgClaimAnmlResponse> {
    const data = MsgClaimAnml.encode(request).finish();
    const promise = this.rpc.request(this.service, "ClaimAnml", data);
    return promise.then((data) => MsgClaimAnmlResponse.decode(new BinaryReader(data)));
  }

  SetCaretaker(request: MsgSetCaretaker): Promise<MsgSetCaretakerResponse> {
    const data = MsgSetCaretaker.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetCaretaker", data);
    return promise.then((data) => MsgSetCaretakerResponse.decode(new BinaryReader(data)));
  }

  BindReferrer(request: MsgBindReferrer): Promise<MsgBindReferrerResponse> {
    const data = MsgBindReferrer.encode(request).finish();
    const promise = this.rpc.request(this.service, "BindReferrer", data);
    return promise.then((data) => MsgBindReferrerResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
