// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: earth/shieldedstaking/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "earth.shieldedstaking.v1";

/** Params defines the parameters of private staking. */
export interface Params {
  /**
   * epoch_seconds is the length of an epoch. Delegations and undelegations
   * queued during an epoch are executed, and rewards compounded, at its end.
   */
  epochSeconds: number;
  /**
   * min_position is the smallest derth a Groundworks position may lock.
   * Positions are weighed per validator (one Groundworks voter each), so no
   * epoch work grows with their number; this only keeps dust out.
   */
  minPosition: string;
  /**
   * stake_root_window_seconds is how long a superseded stake-tree root stays
   * an anchor (the latest never expires; a vote's snapshot root is accepted
   * for its proposal).
   */
  stakeRootWindowSeconds: number;
  /**
   * min_delegation is the smallest private delegation, in uerth, and the
   * least derth one may mint. It keeps validator books from being created
   * for dust (every book is processed at epoch end) and bounds the rounding
   * a donation to the validator's rewards pool can inflict on a delegator.
   */
  minDelegation: string;
}

function createBaseParams(): Params {
  return { epochSeconds: 0, minPosition: "", stakeRootWindowSeconds: 0, minDelegation: "" };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.epochSeconds !== 0) {
      writer.uint32(8).uint64(message.epochSeconds);
    }
    if (message.minPosition !== "") {
      writer.uint32(18).string(message.minPosition);
    }
    if (message.stakeRootWindowSeconds !== 0) {
      writer.uint32(32).uint64(message.stakeRootWindowSeconds);
    }
    if (message.minDelegation !== "") {
      writer.uint32(42).string(message.minDelegation);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseParams();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.epochSeconds = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.minPosition = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.stakeRootWindowSeconds = longToNumber(reader.uint64());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.minDelegation = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Params {
    return {
      epochSeconds: isSet(object.epochSeconds)
        ? globalThis.Number(object.epochSeconds)
        : isSet(object.epoch_seconds)
        ? globalThis.Number(object.epoch_seconds)
        : 0,
      minPosition: isSet(object.minPosition)
        ? globalThis.String(object.minPosition)
        : isSet(object.min_position)
        ? globalThis.String(object.min_position)
        : "",
      stakeRootWindowSeconds: isSet(object.stakeRootWindowSeconds)
        ? globalThis.Number(object.stakeRootWindowSeconds)
        : isSet(object.stake_root_window_seconds)
        ? globalThis.Number(object.stake_root_window_seconds)
        : 0,
      minDelegation: isSet(object.minDelegation)
        ? globalThis.String(object.minDelegation)
        : isSet(object.min_delegation)
        ? globalThis.String(object.min_delegation)
        : "",
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.epochSeconds !== 0) {
      obj.epochSeconds = Math.round(message.epochSeconds);
    }
    if (message.minPosition !== "") {
      obj.minPosition = message.minPosition;
    }
    if (message.stakeRootWindowSeconds !== 0) {
      obj.stakeRootWindowSeconds = Math.round(message.stakeRootWindowSeconds);
    }
    if (message.minDelegation !== "") {
      obj.minDelegation = message.minDelegation;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.epochSeconds = object.epochSeconds ?? 0;
    message.minPosition = object.minPosition ?? "";
    message.stakeRootWindowSeconds = object.stakeRootWindowSeconds ?? 0;
    message.minDelegation = object.minDelegation ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
