// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: earth/shielded/v1/shielded.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "earth.shielded.v1";

/**
 * Action is one spend and one output of a shielded bundle (circuits/action),
 * either of which may be a dummy, and the proof of it. Public input order:
 * anchor, nullifier, commitment, cv_x, cv_y, sighash; the chain computes the
 * sighash from the enclosing msg (zk/orchard.Sighash), so it is not carried.
 */
export interface Action {
  /**
   * anchor is the note-tree root the spend is proven against: 32 bytes, a
   * root recorded within root_window_seconds (or one the msg's action
   * handler vouches for). Required of dummy spends too.
   */
  anchor: Uint8Array;
  /**
   * nullifier of the spent note, 32 bytes, distinct across the msg. A dummy
   * (value-0) spend still publishes, and spends, a fresh nullifier.
   */
  nullifier: Uint8Array;
  /** commitment of the output note, 32 bytes, appended to the tree. */
  commitment: Uint8Array;
  /**
   * cv is the action's value commitment on Grumpkin, x || y, 64 bytes:
   * cv = v_spend*G(asset_spend) - v_out*G(asset_out) + rcv*R.
   */
  cv: Uint8Array;
  /**
   * ciphertext is the output note encrypted to its owner, emitted for
   * wallets to trial-decrypt. Bound by the sighash.
   */
  ciphertext: Uint8Array;
  /** proof is the bb v5.0.0 UltraHonk proof of the action circuit. */
  proof: Uint8Array;
}

/**
 * ValueBalance is value of one denom leaving the pool through a bundle: its
 * spends exceed its outputs by amount. Only positive balances exist.
 */
export interface ValueBalance {
  denom: string;
  amount: number;
}

/**
 * Bundle is an Orchard-style shielded bundle: at least two actions, the
 * public value balance per denom, and the binding signature (Schnorr over
 * Grumpkin, zk/orchard) proving the actions' value commitments sum to the
 * balances. The enclosing msg says where each balance goes (the fee, an
 * unshield receiver, a module); the private ante checks it is spent exactly.
 */
export interface Bundle {
  actions: Action[];
  /** balances, one per denom, each positive. */
  balances: ValueBalance[];
  /** binding_sig is Rn.x || Rn.y || s, 96 bytes, over the msg's sighash. */
  bindingSig: Uint8Array;
}

/**
 * Asset is a denom admitted to the pool and its in-circuit id,
 * asset_id = zk/privacy.AssetID(denom).
 */
export interface Asset {
  denom: string;
  /** asset_id is the 32-byte big-endian field element. */
  assetId: Uint8Array;
}

/**
 * Turnstile counts what has entered and left the pool for one denom. The
 * module's bank balance of the denom equals in - out, always.
 */
export interface Turnstile {
  denom: string;
  in: string;
  out: string;
}

/**
 * RootRecord is a note-tree root recorded at the end of a block that changed
 * the tree.
 */
export interface RootRecord {
  root: Uint8Array;
  /** height of the block that produced it. */
  height: number;
  /** time of that block, unix seconds. The window is measured from here. */
  time: number;
  /** tree_size is the leaf count at this root. */
  treeSize: number;
}

function createBaseAction(): Action {
  return {
    anchor: new Uint8Array(0),
    nullifier: new Uint8Array(0),
    commitment: new Uint8Array(0),
    cv: new Uint8Array(0),
    ciphertext: new Uint8Array(0),
    proof: new Uint8Array(0),
  };
}

export const Action: MessageFns<Action> = {
  encode(message: Action, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.anchor.length !== 0) {
      writer.uint32(10).bytes(message.anchor);
    }
    if (message.nullifier.length !== 0) {
      writer.uint32(18).bytes(message.nullifier);
    }
    if (message.commitment.length !== 0) {
      writer.uint32(26).bytes(message.commitment);
    }
    if (message.cv.length !== 0) {
      writer.uint32(34).bytes(message.cv);
    }
    if (message.ciphertext.length !== 0) {
      writer.uint32(42).bytes(message.ciphertext);
    }
    if (message.proof.length !== 0) {
      writer.uint32(50).bytes(message.proof);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Action {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseAction();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.anchor = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.nullifier = reader.bytes();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.commitment = reader.bytes();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.cv = reader.bytes();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.ciphertext = reader.bytes();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.proof = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Action {
    return {
      anchor: isSet(object.anchor) ? bytesFromBase64(object.anchor) : new Uint8Array(0),
      nullifier: isSet(object.nullifier) ? bytesFromBase64(object.nullifier) : new Uint8Array(0),
      commitment: isSet(object.commitment) ? bytesFromBase64(object.commitment) : new Uint8Array(0),
      cv: isSet(object.cv) ? bytesFromBase64(object.cv) : new Uint8Array(0),
      ciphertext: isSet(object.ciphertext) ? bytesFromBase64(object.ciphertext) : new Uint8Array(0),
      proof: isSet(object.proof) ? bytesFromBase64(object.proof) : new Uint8Array(0),
    };
  },

  toJSON(message: Action): unknown {
    const obj: any = {};
    if (message.anchor.length !== 0) {
      obj.anchor = base64FromBytes(message.anchor);
    }
    if (message.nullifier.length !== 0) {
      obj.nullifier = base64FromBytes(message.nullifier);
    }
    if (message.commitment.length !== 0) {
      obj.commitment = base64FromBytes(message.commitment);
    }
    if (message.cv.length !== 0) {
      obj.cv = base64FromBytes(message.cv);
    }
    if (message.ciphertext.length !== 0) {
      obj.ciphertext = base64FromBytes(message.ciphertext);
    }
    if (message.proof.length !== 0) {
      obj.proof = base64FromBytes(message.proof);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Action>, I>>(base?: I): Action {
    return Action.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Action>, I>>(object: I): Action {
    const message = createBaseAction();
    message.anchor = object.anchor ?? new Uint8Array(0);
    message.nullifier = object.nullifier ?? new Uint8Array(0);
    message.commitment = object.commitment ?? new Uint8Array(0);
    message.cv = object.cv ?? new Uint8Array(0);
    message.ciphertext = object.ciphertext ?? new Uint8Array(0);
    message.proof = object.proof ?? new Uint8Array(0);
    return message;
  },
};

function createBaseValueBalance(): ValueBalance {
  return { denom: "", amount: 0 };
}

export const ValueBalance: MessageFns<ValueBalance> = {
  encode(message: ValueBalance, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.denom !== "") {
      writer.uint32(10).string(message.denom);
    }
    if (message.amount !== 0) {
      writer.uint32(16).uint64(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValueBalance {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseValueBalance();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.denom = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.amount = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ValueBalance {
    return {
      denom: isSet(object.denom) ? globalThis.String(object.denom) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
    };
  },

  toJSON(message: ValueBalance): unknown {
    const obj: any = {};
    if (message.denom !== "") {
      obj.denom = message.denom;
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValueBalance>, I>>(base?: I): ValueBalance {
    return ValueBalance.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValueBalance>, I>>(object: I): ValueBalance {
    const message = createBaseValueBalance();
    message.denom = object.denom ?? "";
    message.amount = object.amount ?? 0;
    return message;
  },
};

function createBaseBundle(): Bundle {
  return { actions: [], balances: [], bindingSig: new Uint8Array(0) };
}

export const Bundle: MessageFns<Bundle> = {
  encode(message: Bundle, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.actions) {
      Action.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.balances) {
      ValueBalance.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.bindingSig.length !== 0) {
      writer.uint32(26).bytes(message.bindingSig);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Bundle {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBundle();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.actions.push(Action.decode(reader, reader.uint32()));
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.balances.push(ValueBalance.decode(reader, reader.uint32()));
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.bindingSig = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Bundle {
    return {
      actions: globalThis.Array.isArray(object?.actions) ? object.actions.map((e: any) => Action.fromJSON(e)) : [],
      balances: globalThis.Array.isArray(object?.balances)
        ? object.balances.map((e: any) => ValueBalance.fromJSON(e))
        : [],
      bindingSig: isSet(object.bindingSig)
        ? bytesFromBase64(object.bindingSig)
        : isSet(object.binding_sig)
        ? bytesFromBase64(object.binding_sig)
        : new Uint8Array(0),
    };
  },

  toJSON(message: Bundle): unknown {
    const obj: any = {};
    if (message.actions?.length) {
      obj.actions = message.actions.map((e) => Action.toJSON(e));
    }
    if (message.balances?.length) {
      obj.balances = message.balances.map((e) => ValueBalance.toJSON(e));
    }
    if (message.bindingSig.length !== 0) {
      obj.bindingSig = base64FromBytes(message.bindingSig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Bundle>, I>>(base?: I): Bundle {
    return Bundle.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Bundle>, I>>(object: I): Bundle {
    const message = createBaseBundle();
    message.actions = object.actions?.map((e) => Action.fromPartial(e)) || [];
    message.balances = object.balances?.map((e) => ValueBalance.fromPartial(e)) || [];
    message.bindingSig = object.bindingSig ?? new Uint8Array(0);
    return message;
  },
};

function createBaseAsset(): Asset {
  return { denom: "", assetId: new Uint8Array(0) };
}

export const Asset: MessageFns<Asset> = {
  encode(message: Asset, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.denom !== "") {
      writer.uint32(10).string(message.denom);
    }
    if (message.assetId.length !== 0) {
      writer.uint32(18).bytes(message.assetId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Asset {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseAsset();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.denom = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.assetId = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Asset {
    return {
      denom: isSet(object.denom) ? globalThis.String(object.denom) : "",
      assetId: isSet(object.assetId)
        ? bytesFromBase64(object.assetId)
        : isSet(object.asset_id)
        ? bytesFromBase64(object.asset_id)
        : new Uint8Array(0),
    };
  },

  toJSON(message: Asset): unknown {
    const obj: any = {};
    if (message.denom !== "") {
      obj.denom = message.denom;
    }
    if (message.assetId.length !== 0) {
      obj.assetId = base64FromBytes(message.assetId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Asset>, I>>(base?: I): Asset {
    return Asset.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Asset>, I>>(object: I): Asset {
    const message = createBaseAsset();
    message.denom = object.denom ?? "";
    message.assetId = object.assetId ?? new Uint8Array(0);
    return message;
  },
};

function createBaseTurnstile(): Turnstile {
  return { denom: "", in: "", out: "" };
}

export const Turnstile: MessageFns<Turnstile> = {
  encode(message: Turnstile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.denom !== "") {
      writer.uint32(10).string(message.denom);
    }
    if (message.in !== "") {
      writer.uint32(18).string(message.in);
    }
    if (message.out !== "") {
      writer.uint32(26).string(message.out);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Turnstile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseTurnstile();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.denom = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.in = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.out = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Turnstile {
    return {
      denom: isSet(object.denom) ? globalThis.String(object.denom) : "",
      in: isSet(object.in) ? globalThis.String(object.in) : "",
      out: isSet(object.out) ? globalThis.String(object.out) : "",
    };
  },

  toJSON(message: Turnstile): unknown {
    const obj: any = {};
    if (message.denom !== "") {
      obj.denom = message.denom;
    }
    if (message.in !== "") {
      obj.in = message.in;
    }
    if (message.out !== "") {
      obj.out = message.out;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Turnstile>, I>>(base?: I): Turnstile {
    return Turnstile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Turnstile>, I>>(object: I): Turnstile {
    const message = createBaseTurnstile();
    message.denom = object.denom ?? "";
    message.in = object.in ?? "";
    message.out = object.out ?? "";
    return message;
  },
};

function createBaseRootRecord(): RootRecord {
  return { root: new Uint8Array(0), height: 0, time: 0, treeSize: 0 };
}

export const RootRecord: MessageFns<RootRecord> = {
  encode(message: RootRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.root.length !== 0) {
      writer.uint32(10).bytes(message.root);
    }
    if (message.height !== 0) {
      writer.uint32(16).int64(message.height);
    }
    if (message.time !== 0) {
      writer.uint32(24).int64(message.time);
    }
    if (message.treeSize !== 0) {
      writer.uint32(32).uint64(message.treeSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RootRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRootRecord();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.root = reader.bytes();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.height = longToNumber(reader.int64());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.time = longToNumber(reader.int64());
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.treeSize = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): RootRecord {
    return {
      root: isSet(object.root) ? bytesFromBase64(object.root) : new Uint8Array(0),
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
      time: isSet(object.time) ? globalThis.Number(object.time) : 0,
      treeSize: isSet(object.treeSize)
        ? globalThis.Number(object.treeSize)
        : isSet(object.tree_size)
        ? globalThis.Number(object.tree_size)
        : 0,
    };
  },

  toJSON(message: RootRecord): unknown {
    const obj: any = {};
    if (message.root.length !== 0) {
      obj.root = base64FromBytes(message.root);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    if (message.time !== 0) {
      obj.time = Math.round(message.time);
    }
    if (message.treeSize !== 0) {
      obj.treeSize = Math.round(message.treeSize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RootRecord>, I>>(base?: I): RootRecord {
    return RootRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RootRecord>, I>>(object: I): RootRecord {
    const message = createBaseRootRecord();
    message.root = object.root ?? new Uint8Array(0);
    message.height = object.height ?? 0;
    message.time = object.time ?? 0;
    message.treeSize = object.treeSize ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
