// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: earth/shielded/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Coin } from "../../../cosmos/base/v1beta1/coin";
import { Params } from "./params";
import { Bundle } from "./shielded";

export const protobufPackage = "earth.shielded.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (x/gov by default). */
  authority: string;
  /** params defines the module parameters to update. All must be supplied. */
  params: Params | undefined;
}

/** MsgUpdateParamsResponse is empty. */
export interface MsgUpdateParamsResponse {
}

/**
 * MsgRegisterAsset admits denom to the pool. Admission is permanent: notes
 * of a denom can always be spent and unshielded.
 */
export interface MsgRegisterAsset {
  /** authority is the address that controls the module (x/gov by default). */
  authority: string;
  /** denom to admit. */
  denom: string;
}

/** MsgRegisterAssetResponse returns the denom's asset id. */
export interface MsgRegisterAssetResponse {
  assetId: Uint8Array;
}

/**
 * MsgShield moves amount from sender into the pool and appends the note
 * cm = H(TAG_CM, AssetID(amount.denom), amount.amount, pc). The chain needs
 * no proof: the asset and value are public, and pc hides the owner. Signed
 * and fee-paying like any transparent tx.
 */
export interface MsgShield {
  sender: string;
  /** amount of a registered denom, at most 2^64 - 1 (note values are u64). */
  amount:
    | Coin
    | undefined;
  /** pc = H(TAG_PC, owner_pk, rho, rcm), 32 bytes. */
  pc: Uint8Array;
  /**
   * ciphertext is optional: the note encrypted to its owner, when the owner
   * is not the sender (a gas grant, a payment). Emitted, never stored.
   */
  ciphertext: Uint8Array;
}

/** MsgShieldResponse returns the note's position and commitment. */
export interface MsgShieldResponse {
  position: number;
  commitment: Uint8Array;
}

/**
 * MsgSend spends shielded notes through one bundle. It has NO signer: its
 * signers are defined as empty (x/tx CustomGetSigner), it travels in a tx
 * with no signatures, and its fee is paid from the pool out of the bundle's
 * uerth balance. Authorization is the proofs and the binding signature;
 * replay protection is the nullifiers.
 *
 * Release map: the bundle's uerth balance pays fee to fee_collector; every
 * other unit of every balance (the uerth rest included) goes to receiver.
 * With no receiver the balances must be exactly the fee.
 *
 * sighash = zk/orchard.Sighash("/earth.shielded.v1.MsgSend", chain_id,
 * [bundle], Bytes(receiver address bytes), fee), so neither the receiver,
 * the fee, a ciphertext nor any balance can be changed by whoever relays it.
 */
export interface MsgSend {
  bundle:
    | Bundle
    | undefined;
  /**
   * receiver gets every balance less the fee. Required exactly when the
   * balances exceed the fee.
   */
  receiver: string;
  /**
   * fee is the uerth the bundle pays to fee_collector; the tx's declared fee
   * must equal it. An unshield of uerth pays it out of what it releases (a
   * fee from output), with no separate fee note.
   */
  fee: number;
}

/**
 * MsgSendResponse returns the positions of the bundle's new notes, in
 * action order.
 */
export interface MsgSendResponse {
  positions: number[];
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateParams();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.authority = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.params = Params.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateParamsResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgRegisterAsset(): MsgRegisterAsset {
  return { authority: "", denom: "" };
}

export const MsgRegisterAsset: MessageFns<MsgRegisterAsset> = {
  encode(message: MsgRegisterAsset, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.denom !== "") {
      writer.uint32(18).string(message.denom);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterAsset {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgRegisterAsset();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.authority = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.denom = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgRegisterAsset {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      denom: isSet(object.denom) ? globalThis.String(object.denom) : "",
    };
  },

  toJSON(message: MsgRegisterAsset): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.denom !== "") {
      obj.denom = message.denom;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterAsset>, I>>(base?: I): MsgRegisterAsset {
    return MsgRegisterAsset.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterAsset>, I>>(object: I): MsgRegisterAsset {
    const message = createBaseMsgRegisterAsset();
    message.authority = object.authority ?? "";
    message.denom = object.denom ?? "";
    return message;
  },
};

function createBaseMsgRegisterAssetResponse(): MsgRegisterAssetResponse {
  return { assetId: new Uint8Array(0) };
}

export const MsgRegisterAssetResponse: MessageFns<MsgRegisterAssetResponse> = {
  encode(message: MsgRegisterAssetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.assetId.length !== 0) {
      writer.uint32(10).bytes(message.assetId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterAssetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgRegisterAssetResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.assetId = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgRegisterAssetResponse {
    return {
      assetId: isSet(object.assetId)
        ? bytesFromBase64(object.assetId)
        : isSet(object.asset_id)
        ? bytesFromBase64(object.asset_id)
        : new Uint8Array(0),
    };
  },

  toJSON(message: MsgRegisterAssetResponse): unknown {
    const obj: any = {};
    if (message.assetId.length !== 0) {
      obj.assetId = base64FromBytes(message.assetId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterAssetResponse>, I>>(base?: I): MsgRegisterAssetResponse {
    return MsgRegisterAssetResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterAssetResponse>, I>>(object: I): MsgRegisterAssetResponse {
    const message = createBaseMsgRegisterAssetResponse();
    message.assetId = object.assetId ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgShield(): MsgShield {
  return { sender: "", amount: undefined, pc: new Uint8Array(0), ciphertext: new Uint8Array(0) };
}

export const MsgShield: MessageFns<MsgShield> = {
  encode(message: MsgShield, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sender !== "") {
      writer.uint32(10).string(message.sender);
    }
    if (message.amount !== undefined) {
      Coin.encode(message.amount, writer.uint32(18).fork()).join();
    }
    if (message.pc.length !== 0) {
      writer.uint32(26).bytes(message.pc);
    }
    if (message.ciphertext.length !== 0) {
      writer.uint32(34).bytes(message.ciphertext);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgShield {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgShield();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.sender = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.amount = Coin.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.pc = reader.bytes();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.ciphertext = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgShield {
    return {
      sender: isSet(object.sender) ? globalThis.String(object.sender) : "",
      amount: isSet(object.amount) ? Coin.fromJSON(object.amount) : undefined,
      pc: isSet(object.pc) ? bytesFromBase64(object.pc) : new Uint8Array(0),
      ciphertext: isSet(object.ciphertext) ? bytesFromBase64(object.ciphertext) : new Uint8Array(0),
    };
  },

  toJSON(message: MsgShield): unknown {
    const obj: any = {};
    if (message.sender !== "") {
      obj.sender = message.sender;
    }
    if (message.amount !== undefined) {
      obj.amount = Coin.toJSON(message.amount);
    }
    if (message.pc.length !== 0) {
      obj.pc = base64FromBytes(message.pc);
    }
    if (message.ciphertext.length !== 0) {
      obj.ciphertext = base64FromBytes(message.ciphertext);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgShield>, I>>(base?: I): MsgShield {
    return MsgShield.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgShield>, I>>(object: I): MsgShield {
    const message = createBaseMsgShield();
    message.sender = object.sender ?? "";
    message.amount = (object.amount !== undefined && object.amount !== null)
      ? Coin.fromPartial(object.amount)
      : undefined;
    message.pc = object.pc ?? new Uint8Array(0);
    message.ciphertext = object.ciphertext ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgShieldResponse(): MsgShieldResponse {
  return { position: 0, commitment: new Uint8Array(0) };
}

export const MsgShieldResponse: MessageFns<MsgShieldResponse> = {
  encode(message: MsgShieldResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.position !== 0) {
      writer.uint32(8).uint64(message.position);
    }
    if (message.commitment.length !== 0) {
      writer.uint32(18).bytes(message.commitment);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgShieldResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgShieldResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.position = longToNumber(reader.uint64());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.commitment = reader.bytes();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgShieldResponse {
    return {
      position: isSet(object.position) ? globalThis.Number(object.position) : 0,
      commitment: isSet(object.commitment) ? bytesFromBase64(object.commitment) : new Uint8Array(0),
    };
  },

  toJSON(message: MsgShieldResponse): unknown {
    const obj: any = {};
    if (message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    if (message.commitment.length !== 0) {
      obj.commitment = base64FromBytes(message.commitment);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgShieldResponse>, I>>(base?: I): MsgShieldResponse {
    return MsgShieldResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgShieldResponse>, I>>(object: I): MsgShieldResponse {
    const message = createBaseMsgShieldResponse();
    message.position = object.position ?? 0;
    message.commitment = object.commitment ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgSend(): MsgSend {
  return { bundle: undefined, receiver: "", fee: 0 };
}

export const MsgSend: MessageFns<MsgSend> = {
  encode(message: MsgSend, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bundle !== undefined) {
      Bundle.encode(message.bundle, writer.uint32(10).fork()).join();
    }
    if (message.receiver !== "") {
      writer.uint32(18).string(message.receiver);
    }
    if (message.fee !== 0) {
      writer.uint32(24).uint64(message.fee);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSend {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgSend();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.bundle = Bundle.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.receiver = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.fee = longToNumber(reader.uint64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgSend {
    return {
      bundle: isSet(object.bundle) ? Bundle.fromJSON(object.bundle) : undefined,
      receiver: isSet(object.receiver) ? globalThis.String(object.receiver) : "",
      fee: isSet(object.fee) ? globalThis.Number(object.fee) : 0,
    };
  },

  toJSON(message: MsgSend): unknown {
    const obj: any = {};
    if (message.bundle !== undefined) {
      obj.bundle = Bundle.toJSON(message.bundle);
    }
    if (message.receiver !== "") {
      obj.receiver = message.receiver;
    }
    if (message.fee !== 0) {
      obj.fee = Math.round(message.fee);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSend>, I>>(base?: I): MsgSend {
    return MsgSend.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSend>, I>>(object: I): MsgSend {
    const message = createBaseMsgSend();
    message.bundle = (object.bundle !== undefined && object.bundle !== null)
      ? Bundle.fromPartial(object.bundle)
      : undefined;
    message.receiver = object.receiver ?? "";
    message.fee = object.fee ?? 0;
    return message;
  },
};

function createBaseMsgSendResponse(): MsgSendResponse {
  return { positions: [] };
}

export const MsgSendResponse: MessageFns<MsgSendResponse> = {
  encode(message: MsgSendResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.positions) {
      writer.uint64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSendResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgSendResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag === 8) {
              message.positions.push(longToNumber(reader.uint64()));

              continue;
            }

            if (tag === 10) {
              const end2 = reader.uint32() + reader.pos;
              while (reader.pos < end2) {
                message.positions.push(longToNumber(reader.uint64()));
              }

              continue;
            }

            break;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgSendResponse {
    return {
      positions: globalThis.Array.isArray(object?.positions)
        ? object.positions.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: MsgSendResponse): unknown {
    const obj: any = {};
    if (message.positions?.length) {
      obj.positions = message.positions.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSendResponse>, I>>(base?: I): MsgSendResponse {
    return MsgSendResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSendResponse>, I>>(object: I): MsgSendResponse {
    const message = createBaseMsgSendResponse();
    message.positions = object.positions?.map((e) => e) || [];
    return message;
  },
};

/** Msg defines the shielded pool's Msg service. */
export interface Msg {
  /** UpdateParams updates the module parameters (governance). */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** RegisterAsset admits a denom to the pool (governance). */
  RegisterAsset(request: MsgRegisterAsset): Promise<MsgRegisterAssetResponse>;
  /** Shield moves the signer's coins into the pool as one note. */
  Shield(request: MsgShield): Promise<MsgShieldResponse>;
  /**
   * Send spends notes through a bundle: a private send, and optionally an
   * unshield to a transparent receiver. Unsigned; see MsgSend.
   */
  Send(request: MsgSend): Promise<MsgSendResponse>;
}

export const MsgServiceName = "earth.shielded.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.RegisterAsset = this.RegisterAsset.bind(this);
    this.Shield = this.Shield.bind(this);
    this.Send = this.Send.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  RegisterAsset(request: MsgRegisterAsset): Promise<MsgRegisterAssetResponse> {
    const data = MsgRegisterAsset.encode(request).finish();
    const promise = this.rpc.request(this.service, "RegisterAsset", data);
    return promise.then((data) => MsgRegisterAssetResponse.decode(new BinaryReader(data)));
  }

  Shield(request: MsgShield): Promise<MsgShieldResponse> {
    const data = MsgShield.encode(request).finish();
    const promise = this.rpc.request(this.service, "Shield", data);
    return promise.then((data) => MsgShieldResponse.decode(new BinaryReader(data)));
  }

  Send(request: MsgSend): Promise<MsgSendResponse> {
    const data = MsgSend.encode(request).finish();
    const promise = this.rpc.request(this.service, "Send", data);
    return promise.then((data) => MsgSendResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
