name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Deploy and Build on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Exit on error

            HOME_DIR=/home/secret/earth-mainnet-app
            BUILD_DIR=$HOME_DIR/build
            SERVER_DIR=$HOME_DIR/server
            DEPLOY_DIR=/var/www/erth

            mkdir -p $HOME_DIR

            # Clone or update repository
            cd $HOME_DIR
            if [ -d ".git" ]; then
              git fetch origin
              git reset --hard origin/main
              git clean -fd
            else
              git clone https://github.com/zenopie/erth-mainnet-app.git .
            fi

            # Install Node.js for front-end build
            export NVM_DIR="$HOME/.nvm"
            if [ ! -d "$NVM_DIR" ]; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            fi
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm install 18.20.7
            nvm use 18.20.7
            nvm alias default 18.20.7

            # Build front-end
            if [ -f package.json ]; then
              npm install
              npm update
              rm -rf $BUILD_DIR/*
              npm run build
            else
              echo "package.json not found!"
              exit 1
            fi

            # Copy front-end build to deployment directory
            rm -rf $DEPLOY_DIR/*
            cp -r $BUILD_DIR/* $DEPLOY_DIR/

            # Install Docker
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker secret
            fi

            # Build and run Docker container
            cd $SERVER_DIR
            if [ ! -f WALLET_KEY.txt ]; then
              echo "WALLET_KEY.txt not found in $SERVER_DIR!"
              exit 1
            fi
            docker build -t erth-network-server .
            docker stop erth-network-server || true
            docker rm erth-network-server || true
            docker run -d --name erth-network-server -p 5000:5000 --restart always erth-network-server